using ACE.Entity.Enum;using ACE.Common;using ACE.Server.Factories.Enum;using ACE.Server.Factories.Entity;using ACE.Server.Factories.Tables;using ACE.Server.WorldObjects;using ACE.Database.Models.World;using Server=ACE.Server;
namespace log4net{public interface ILog{void Error(object v);}public class Log:ILog{public void Error(object v){}public void Warn(object v){}}public static class LogManager{public static ILog GetLogger(Type t)=>new Log();}}
namespace ACE.Common{public static class ThreadSafeRandom{public static double Value;public static int Draws;public static double Next(float min,float max){Draws++;return Value*(max-min)+min;}public static int Next(int min,int max){Draws++;return min+(int)(Value*(max-min+1));}}}
namespace ACE.Database.Models.World{public class TreasureDeath{public int Tier,TreasureType=1;public float LootQualityMod;}}
namespace ACE.Server.Entity{public class Spell{public uint Level;public Spell(uint id){Level=id%8+1;}}}
namespace ACE.Server.WorldObjects{public class WorldObject{
public string Name="Cloak";public uint WeenieClassId=1;public WeenieType WeenieType=WeenieType.Clothing;public ItemType ItemType=ItemType.Clothing;public MaterialType? MaterialType,GemType;public int? Value=100,ArmorLevel,ItemMaxMana,ItemWorkmanship;public double? BulkMod,SizeMod;public uint? SpellDID;public Biota Biota=new();public bool HasArmorLevel()=>ArmorLevel>0;public int? ItemMaxLevel,WieldDifficulty,WieldSkillType,WieldDifficulty2,WieldSkillType2;public WieldRequirement WieldRequirements,WieldRequirements2;public uint IconOverlayId;public EquipmentSet? EquipmentSetId;public uint? ProcSpell;public bool ProcSpellSelfTargeted;public int? CloakWeaveProc;public bool IsShield=false;public int? GearCritDamage,GearCritDamageResist,GearDamage,GearDamageResist,GearHealingBoost,GearMaxHealth;public int NumItemsInMaterial=2;public float? Workmanship{get=>ItemWorkmanship/(float)NumItemsInMaterial;set=>ItemWorkmanship=(int)Math.Round(value.Value*NumItemsInMaterial);}}
public class Gem:WorldObject{}public class Biota{public Dictionary<uint,float> PropertiesSpellBook=new();}}
namespace ACE.Server.Factories.Entity{public class TreasureRoll{public TreasureArmorType ArmorType;public TreasureItemType ItemType=TreasureItemType.Cloak;public bool HasArmorLevel(WorldObject w)=>w.ArmorLevel>0;public bool IsClothing=>ItemType==TreasureItemType.Clothing;public bool IsJewelry=>ItemType==TreasureItemType.Jewelry;public bool IsCloak=>ItemType==TreasureItemType.Cloak;}}
// DEFAULT
public class Oracle{static log4net.Log log=new();const float valueFactor=1f/3f,valueNonFactor=1f-valueFactor;static readonly List<int> ItemValue_TierMod=new(){25,50,100,250,500,1000,2000,3000};static readonly List<uint> IconOverlay_ItemMaxLevel=new(){0x6006c34,0x6006c35,0x6006c36,0x6006c37,0x6006c38};static MaterialType GetMaterialType(WorldObject w,int tier)=>GetDefaultMaterialType(w);
// METHODS
public static void Main(){foreach(var tier in new[]{1,4,6,8})foreach(var draw in new[]{0d,.1d,.5d,.75d,.98d}){var w=new WorldObject();ThreadSafeRandom.Value=draw;ThreadSafeRandom.Draws=0;MutateCloak(w,new TreasureDeath{Tier=tier,LootQualityMod=.2f},new TreasureRoll());Console.WriteLine($"{tier}|{draw:R}|{w.ItemMaxLevel},{w.WieldDifficulty},{(int)(w.EquipmentSetId??0)},{w.CloakWeaveProc},{(int)(w.MaterialType??0)},{w.ItemWorkmanship},{w.Value},{w.GearDamage??0},{w.GearDamageResist??0},{(int)w.WieldRequirements}|{w.IconOverlayId},{w.ProcSpell??0}|{w.ProcSpellSelfTargeted}|{ThreadSafeRandom.Draws}");}}}
