<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>disable</Nullable><NoWarn>CS0219</NoWarn></PropertyGroup><ItemGroup><EmbeddedResource Include="scripts/ArmorLevel/armor_level_extremity.txt" LogicalName="ACE.Server.Entity.Mutations.ArmorLevel.armor_level_extremity.txt" />
<EmbeddedResource Include="scripts/ArmorLevel/armor_level_non_extremity.txt" LogicalName="ACE.Server.Entity.Mutations.ArmorLevel.armor_level_non_extremity.txt" />
<EmbeddedResource Include="scripts/ArmorLevel/covenant_armor.txt" LogicalName="ACE.Server.Entity.Mutations.ArmorLevel.covenant_armor.txt" />
<EmbeddedResource Include="scripts/ArmorLevel/covenant_shield.txt" LogicalName="ACE.Server.Entity.Mutations.ArmorLevel.covenant_shield.txt" />
<EmbeddedResource Include="scripts/ArmorLevel/olthoi_armor.txt" LogicalName="ACE.Server.Entity.Mutations.ArmorLevel.olthoi_armor.txt" />
<EmbeddedResource Include="scripts/ArmorLevel/olthoi_shield.txt" LogicalName="ACE.Server.Entity.Mutations.ArmorLevel.olthoi_shield.txt" />
<EmbeddedResource Include="scripts/ArmorLevel/shield_level.txt" LogicalName="ACE.Server.Entity.Mutations.ArmorLevel.shield_level.txt" />
<EmbeddedResource Include="scripts/Casters/caster.txt" LogicalName="ACE.Server.Entity.Mutations.Casters.caster.txt" />
<EmbeddedResource Include="scripts/Casters/caster_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.Casters.caster_elemental.txt" />
<EmbeddedResource Include="scripts/Casters/caster_non_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.Casters.caster_non_elemental.txt" />
<EmbeddedResource Include="scripts/Casters/weapon_defense.txt" LogicalName="ACE.Server.Entity.Mutations.Casters.weapon_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_axe.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_axe.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_dagger.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_dagger.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_dagger_ms.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_dagger_ms.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_mace.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_mace.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_spear.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_spear.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_staff.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_staff.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_sword.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_sword.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_sword_ms.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_sword_ms.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/heavy_unarmed.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.heavy_unarmed.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_axe.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_axe.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_dagger.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_dagger.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_dagger_ms.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_dagger_ms.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_mace.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_mace.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_mace_jitte.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_mace_jitte.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_spear.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_spear.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_staff.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_staff.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_sword.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_sword.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_sword_ms.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_sword_ms.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/light_finesse_unarmed.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.light_finesse_unarmed.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/two_handed_cleaver.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.two_handed_cleaver.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/Damage_WieldDifficulty_DamageVariance/two_handed_spear.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.Damage_WieldDifficulty_DamageVariance.two_handed_spear.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/axe_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.axe_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/dagger_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.dagger_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/mace_jitte_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.mace_jitte_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/mace_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.mace_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/spear_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.spear_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/staff_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.staff_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/sword_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.sword_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/two_handed_axe_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.two_handed_axe_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/two_handed_mace_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.two_handed_mace_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/two_handed_spear_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.two_handed_spear_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/two_handed_sword_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.two_handed_sword_offense_defense.txt" />
<EmbeddedResource Include="scripts/MeleeWeapons/WeaponOffense_WeaponDefense/unarmed_offense_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MeleeWeapons.WeaponOffense_WeaponDefense.unarmed_offense_defense.txt" />
<EmbeddedResource Include="scripts/MissileWeapons/atlatl_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.MissileWeapons.atlatl_elemental.txt" />
<EmbeddedResource Include="scripts/MissileWeapons/atlatl_non_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.MissileWeapons.atlatl_non_elemental.txt" />
<EmbeddedResource Include="scripts/MissileWeapons/bow_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.MissileWeapons.bow_elemental.txt" />
<EmbeddedResource Include="scripts/MissileWeapons/bow_non_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.MissileWeapons.bow_non_elemental.txt" />
<EmbeddedResource Include="scripts/MissileWeapons/crossbow_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.MissileWeapons.crossbow_elemental.txt" />
<EmbeddedResource Include="scripts/MissileWeapons/crossbow_non_elemental.txt" LogicalName="ACE.Server.Entity.Mutations.MissileWeapons.crossbow_non_elemental.txt" />
<EmbeddedResource Include="scripts/MissileWeapons/weapon_defense.txt" LogicalName="ACE.Server.Entity.Mutations.MissileWeapons.weapon_defense.txt" /></ItemGroup></Project>
