//! Vectors generated by unchanged official ACE combat handlers and serializers.
use bace_wire::*;
use serde_json::{Value, json};
fn fixture() -> Value {
    serde_json::from_str(include_str!("../fixtures/messages.json")).unwrap()
}
fn bytes(value: &Value) -> Vec<u8> {
    let s = value["bytes"].as_str().unwrap();
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}
#[test]
fn combat_actions_match_original_handlers() {
    for vector in fixture()["vectors"]["combat"]["actions"]
        .as_array()
        .unwrap()
    {
        let data = bytes(vector);
        let envelope = GameActionEnvelope::decode(&data, 256).unwrap();
        let request = CombatRequest::decode(envelope.action, envelope.payload, 256).unwrap();
        let captured = match request.action {
            CombatAction::TargetedMelee {
                target_id,
                height,
                power,
            } => json!({"target_id":target_id,"height":height,"power_bits":power.to_bits()}),
            CombatAction::TargetedMissile {
                target_id,
                height,
                accuracy,
            } => json!({"target_id":target_id,"height":height,"accuracy_bits":accuracy.to_bits()}),
            CombatAction::ChangeMode(mode) => json!({"mode":mode}),
            CombatAction::CancelAttack => json!({"empty":true}),
            CombatAction::QueryHealth(target_id) => json!({"target_id":target_id}),
        };
        assert_eq!(captured, vector["captured"]);
        assert_eq!(
            request.trailing_bytes,
            vector["trailing_bytes"].as_u64().unwrap() as usize
        );
        for length in 0..envelope.payload.len() - request.trailing_bytes {
            assert!(
                CombatRequest::decode(envelope.action, &envelope.payload[..length], 256).is_err()
            );
        }
    }
}
#[test]
fn combat_events_preserve_float_widening_condition_width_and_queues() {
    let damage = DamageNotification {
        name: "Drudge café",
        damage_type: 4,
        percent: 0.35,
        damage: 37,
        critical: true,
        conditions: 0xffff_ffff_8765_4321,
    };
    for (name, event) in [
        ("done", CombatEvent::AttackDone(0x36)),
        ("commence", CombatEvent::CommenceAttack),
        ("attacker", CombatEvent::Attacker(damage)),
        (
            "defender",
            CombatEvent::Defender {
                damage,
                location: 6,
            },
        ),
        ("evaded_by", CombatEvent::EvadedBy("Drudge café")),
        ("evaded_from", CombatEvent::EvadedAttackFrom("Drudge café")),
        (
            "health",
            CombatEvent::UpdateHealth {
                target_id: 0x80000001,
                fraction: 0.35,
            },
        ),
        ("killer", CombatEvent::KillerNotification("Drudge café")),
        ("victim", CombatEvent::VictimNotification("Drudge café")),
    ] {
        let vector = &fixture()["vectors"]["combat"]["events"][name];
        assert_eq!(
            event.encode(0x50000001, 42, 128, 256).unwrap(),
            bytes(vector),
            "{name}"
        );
        assert_eq!(vector["group"], 9);
    }
}
#[test]
fn combat_effects_match_original_messages() {
    for (name, effect, group) in [
        (
            "sound",
            CombatEffect::Sound {
                object_id: 0x80000001,
                sound_id: 7,
                volume: 0.35,
            },
            10,
        ),
        (
            "script",
            CombatEffect::Script {
                object_id: 0x80000001,
                script_id: 7,
                speed: 0.35,
            },
            10,
        ),
        (
            "killed",
            CombatEffect::PlayerKilled {
                text: "Drudge café",
                victim_id: 0x80000001,
                killer_id: 0x50000001,
            },
            9,
        ),
    ] {
        let vector = &fixture()["vectors"]["combat"]["events"][name];
        assert_eq!(effect.encode(128, 256).unwrap(), bytes(vector));
        assert_eq!(vector["group"], group);
    }
}

#[test]
fn targeted_missile_matches_separate_unchanged_ace_handler_capture() {
    for row in include_str!("../../../crates/network/bace-wire/tests/fixtures/missile.csv")
        .lines()
        .filter(|l| !l.starts_with('#'))
    {
        let p: Vec<_> = row.split(',').collect();
        let data: Vec<_> = p[0]
            .as_bytes()
            .chunks_exact(2)
            .map(|v| u8::from_str_radix(std::str::from_utf8(v).unwrap(), 16).unwrap())
            .collect();
        let CombatAction::TargetedMissile {
            target_id,
            height,
            accuracy,
        } = CombatRequest::decode(
            bace_wire::opcode::GameActionType::TargetedMissileAttack,
            &data,
            12,
        )
        .unwrap()
        .action
        else {
            panic!("missile")
        };
        assert_eq!(
            (target_id, height, accuracy.to_bits()),
            (
                p[1].parse().unwrap(),
                p[2].parse().unwrap(),
                p[3].parse().unwrap()
            )
        );
    }
}
