[package]
name = "bace-loot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Treasure tables and generated items"

[lints]
workspace = true

[dependencies]
bace-content.workspace = true
bace-gameplay-api.workspace = true
bace-random.workspace = true

[dev-dependencies]
serde_json.workspace = true
toml.workspace = true
