using ACE.Entity.Enum;using ACE.Entity.Enum.Properties;using ACE.Server.Factories.Enum;using ACE.Server.Factories.Entity;using ACE.Server.Factories.Tables;using ACE.Server.WorldObjects;using ACE.Database.Models.World;using ACE.Common;
namespace log4net{public interface ILog{void Error(object v);}public class Log:ILog{public void Error(object v){}}public static class LogManager{public static ILog GetLogger(Type t)=>new Log();}}
namespace ACE.Common{public static class ThreadSafeRandom{public static double Value;public static int Draws;public static double Next(float min,float max){Draws++;return Value*(max-min)+min;}public static int Next(int min,int max){Draws++;return min+(int)(Value*(max-min+1));}}}
namespace ACE.Database.Models.World{public class TreasureDeath{public int Tier,TreasureType=1;public float LootQualityMod;}}
namespace ACE.Entity.Enum.Properties{public enum PropertyFloat{ArmorModVsFire}}
namespace ACE.Server.WorldObjects{public class WorldObject{public string Name="oracle";public uint WeenieClassId=1;public bool IsShield;public CoverageMask? ClothingPriority;public int? ArmorLevel;public double? Fire=1;public WieldRequirement WieldRequirements,WieldRequirements2;public int? WieldSkillType,WieldDifficulty,WieldSkillType2,WieldDifficulty2;public int? GearCritDamage,GearCritDamageResist,GearDamage,GearDamageResist,GearHealingBoost,GearMaxHealth;public double? GetProperty(PropertyFloat p)=>Fire;public void SetProperty(PropertyFloat p,double v){Fire=v;}}}
namespace ACE.Server.Factories.Entity{public class TreasureRoll{public TreasureArmorType ArmorType;public TreasureItemType ItemType;public bool HasArmorLevel(WorldObject w)=>w.ArmorLevel>0;public bool IsClothing=>ItemType==TreasureItemType.Clothing;public bool IsJewelry=>ItemType==TreasureItemType.Jewelry;public bool IsCloak=>ItemType==TreasureItemType.Cloak;}}
public class Oracle{static log4net.ILog log=new log4net.Log();
// METHODS
public static void Main(){foreach(var scenario in Enumerable.Range(0,9))foreach(var tier in new[]{1,2,6,8})foreach(var draw in new[]{0d,.1d,.5d,.98d}){
 var w=new WorldObject{ArmorLevel=100,ClothingPriority=CoverageMask.OuterwearChest,WieldRequirements=WieldRequirement.Level,WieldDifficulty=150};var r=new TreasureRoll{ItemType=TreasureItemType.Armor,ArmorType=TreasureArmorType.Leather};if(scenario==1)w.IsShield=true;if(scenario==2){w.IsShield=true;r.ArmorType=TreasureArmorType.Covenant;}if(scenario==3)r.ArmorType=TreasureArmorType.Olthoi;if(scenario==4)w.ClothingPriority=CoverageMask.Head;if(scenario==5){w.ArmorLevel=0;r.ItemType=TreasureItemType.Jewelry;r.ArmorType=0;}if(scenario==6){w.ArmorLevel=0;r.ItemType=TreasureItemType.Clothing;r.ArmorType=0;}if(scenario==7){r.ArmorType=TreasureArmorType.Society;w.WieldRequirements=WieldRequirement.IntStat;}if(scenario==8)w.WieldRequirements=WieldRequirement.RawSkill;
 var script=GetMutationScript_ArmorLevel(w,r);var p=new TreasureDeath{Tier=tier,LootQualityMod=.2f};ThreadSafeRandom.Value=draw;ThreadSafeRandom.Draws=0;TryMutateArmorModVsType(w,p,PropertyFloat.ArmorModVsFire);TryMutateGearRating(w,p,r);var set=EquipmentSetChance.Roll(w,p,r);
 Console.WriteLine($"{scenario}|{tier}|{draw:R}|{script}|{w.Fire:R}|{w.GearCritDamage??0},{w.GearCritDamageResist??0},{w.GearDamage??0},{w.GearDamageResist??0},{w.GearHealingBoost??0},{w.GearMaxHealth??0}|{(int)w.WieldRequirements},{w.WieldDifficulty??0},{(int)w.WieldRequirements2},{w.WieldDifficulty2??0}|{(int)(set??0)}|{ThreadSafeRandom.Draws}");
}}}
