#!/usr/bin/env python3
"""Run unchanged pinned SendInventoryAndWieldedItems with deterministic containers."""
from pathlib import Path
import tempfile,subprocess,hashlib
ROOT=Path(__file__).resolve().parents[4];SRC=ROOT/'.reference/ACE-47edade3bd3f6044b676d4eb877c4965c7eda62b/Source';f=SRC/'ACE.Server/WorldObjects/Player_Networking.cs';s=f.read_text();a=s.index('public void SendInventoryAndWieldedItems(');i=s.index('{',a)+1;depth=1
while depth:depth+=(s[i]=='{')-(s[i]=='}');i+=1
h='''using System;using System.Collections.Generic;class WorldObject{public uint Id;public Player Wielder;}class Container:WorldObject{public Dictionary<uint,WorldObject>Inventory=new();}class GameMessageCreateObject{public WorldObject Item;public GameMessageCreateObject(WorldObject w){Item=w;}}class GameEventViewContents{public Container Item;public GameEventViewContents(Session s,Container c){Item=c;}}class Network{public void EnqueueSend(object m){Console.WriteLine(m is GameMessageCreateObject c?"create"+c.Item.Id:"contents"+((GameEventViewContents)m).Item.Id);}}class Session{public Network Network=new();}class Player{public Session Session=new();public Dictionary<uint,WorldObject>Inventory=new(),EquippedObjects=new();METHOD}class Program{static void Main(){var p=new Player();var bag=new Container{Id=2};bag.Inventory[4]=new WorldObject{Id=4};bag.Inventory[3]=new WorldObject{Id=3};p.Inventory[2]=bag;p.Inventory[5]=new WorldObject{Id=5};p.EquippedObjects[6]=new WorldObject{Id=6};p.SendInventoryAndWieldedItems();}}'''.replace('METHOD',s[a:i])
with tempfile.TemporaryDirectory(prefix='entry-order-') as tmp:
 p=Path(tmp);(p/'Program.cs').write_text(h);(p/'oracle.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>');subprocess.run(['/tmp/bace-crafting-dotnet/dotnet','build','--nologo','-o',str(p/'build')],cwd=p,check=True,stdout=subprocess.DEVNULL);out=subprocess.check_output(['/tmp/bace-crafting-dotnet/dotnet',str(p/'build/oracle.dll')],text=True)
 Path(__file__).parents[1].joinpath('tests/fixtures/entry_order.txt').write_text('# ACE.Server/WorldObjects/Player_Networking.cs '+hashlib.sha256(f.read_bytes()).hexdigest()+'\n'+out)
