using System.Globalization;
using ACE.Server.WorldObjects;
using ACE.Server.WorldObjects.Entity;
using ACE.Entity.Enum;
namespace log4net { public interface ILog{void Warn(string s);void Error(string s);} public class Log:ILog{public void Warn(string s){} public void Error(string s){}} public static class LogManager{public static ILog GetLogger(Type t)=>new Log();}}
namespace ACE.Common{public static class Time{public static double Now;public static double GetUnixTime()=>Now;}}
namespace ACE.Entity.Enum{public enum SkillAdvancementClass{Inactive,Untrained,Trained,Specialized} public enum Skill{ItemTinkering=18}public enum XpType{Proficiency}public enum ShareType{None}}
namespace ACE.Server.WorldObjects.Entity{public class Usage{public uint ResistanceAtLastCheck;public double LastUsedTime;}public class CreatureSkill{public Usage PropertiesSkill=new();public SkillAdvancementClass AdvancementClass;public Skill Skill=Skill.ItemTinkering;public uint ExperienceSpent;public uint ExperienceLeft=>10000-ExperienceSpent;}}
namespace ACE.Server.WorldObjects{public class Player{public bool IsOlthoiPlayer,ChangesDetected;public string Name="Oracle";public uint Level;public long Total,Available,Queued;public CreatureSkill Skill;public bool Granted;public bool IsMaxLevel=>Level==3;public static uint GetMaxLevel()=>3;public long? GetRemainingXP(uint level)=>100000-Total;public void GrantXP(long amount,XpType type,ShareType share){Queued=amount;Granted=true;}public bool HandleActionRaiseSkill(Skill skill,uint amount){if(amount>Available||amount>Skill.ExperienceLeft)return false;Available-=amount;Skill.ExperienceSpent+=amount;return true;} public void Flush(){if(Granted&&Level!=3){Available+=Queued;Total+=Queued;while(Level<3&&Total>=(Level==1?50000:100000))Level++;}}}}
class Program{static void Main(){CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;foreach(bool olthoi in new[]{false,true})foreach(int ac in new[]{1,2,3})foreach(double elapsed in new[]{-1.0,0.0,1.0,450.0,899.0,900.0,1800.0})foreach(uint difficulty in new uint[]{0,1,5,100,501,9999})foreach(long available in new long[]{0,10000})foreach(long total in new long[]{0,99999,100000}){
var skill=new CreatureSkill{AdvancementClass=(SkillAdvancementClass)ac,ExperienceSpent=ac>=2&&difficulty==9999?9999u:0u};skill.PropertiesSkill.ResistanceAtLastCheck=100;skill.PropertiesSkill.LastUsedTime=10000;ACE.Common.Time.Now=10000+elapsed;var player=new Player{IsOlthoiPlayer=olthoi,Level=total==100000?3u:total>=50000?2u:1u,Total=total,Available=available,Skill=skill};ACE.Server.Entity.Proficiency.OnSuccessUse(player,skill,difficulty);player.Flush();Console.WriteLine($"CASE,{olthoi},{ac},{elapsed:R},{difficulty},{available},{total},{skill.PropertiesSkill.ResistanceAtLastCheck},{skill.PropertiesSkill.LastUsedTime:R},{skill.ExperienceSpent},{player.Total},{player.Available},{player.Level},{player.Granted},{player.Queued}");
}}}
