#!/usr/bin/env python3
"""Compile unmodified official QualityFilter decoder on synthetic records."""
from pathlib import Path
import tempfile,subprocess,hashlib
ROOT=Path(__file__).resolve().parents[4];source=ROOT/'.reference/ACE-47edade3bd3f6044b676d4eb877c4965c7eda62b/Source/ACE.DatLoader/FileTypes/QualityFilter.cs'
harness='''using System;using System.IO;using System.Linq;using ACE.DatLoader.FileTypes;class Program{static void Main(){var m=new MemoryStream();var w=new BinaryWriter(m);w.Write(0x0e010001u);for(uint i=1;i<=8;i++)w.Write(i);for(uint i=1;i<=8;i++)for(uint j=0;j<i;j++)w.Write(i*100+j);for(uint i=1;i<=3;i++)w.Write(i);for(uint i=1;i<=3;i++)for(uint j=0;j<i;j++)w.Write(j+1);m.Position=0;var f=new QualityFilter();f.Unpack(new BinaryReader(m));Console.WriteLine(Convert.ToHexString(m.ToArray()));foreach(var list in new[]{f.IntStatFilter,f.Int64StatFilter,f.BoolStatFilter,f.FloatStatFilter,f.DidStatFilter,f.IidStatFilter,f.StringStatFilter,f.PositionStatFilter,f.AttributeStatFilter,f.Attribute2ndStatFilter,f.SkillStatFilter})Console.WriteLine(string.Join(",",list));}}
namespace ACE.DatLoader.FileTypes{public class FileType{public uint Id;public virtual void Unpack(BinaryReader r){}}public enum DatFileType{QualityFilter}public class DatFileTypeAttribute:Attribute{public DatFileTypeAttribute(DatFileType t){}}}'''
with tempfile.TemporaryDirectory(prefix='quality-filter-oracle-') as tmp:
 p=Path(tmp);(p/'Source.cs').write_bytes(source.read_bytes());(p/'Program.cs').write_text(harness);(p/'oracle.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>');subprocess.run(['/tmp/bace-crafting-dotnet/dotnet','build','--nologo','-o',str(p/'build')],cwd=p,check=True);output=subprocess.check_output(['/tmp/bace-crafting-dotnet/dotnet',str(p/'build/oracle.dll')],text=True);(Path(__file__).resolve().parents[1]/'tests/fixtures/quality_filter.txt').write_text('# ACE QualityFilter.cs SHA256 '+hashlib.sha256(source.read_bytes()).hexdigest()+'\n'+output)
