[package]
name = "bace-spawning"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Generators, spawning, despawning and decay"

[lints]
workspace = true

[dependencies]
bace-gameplay-api.workspace = true
bace-types.workspace = true
bace-geometry.workspace = true
bace-random.workspace = true
bace-content.workspace = true
