//! Numeric/name mappings from official ACE enum definitions at
//! 47edade3bd3f6044b676d4eb877c4965c7eda62b (AGPL-3.0-only).

pub(crate) fn resolve(family: &str, name: &str) -> Option<u32> {
    match family {
        "WeenieType" => weenietype(name),
        "DamageType" => damagetype(name),
        "DestinationType" => destinationtype(name),
        "EmoteCategory" => emotecategory(name),
        "MotionStance" => crate::motion_names::motionstance(name),
        "MotionCommand" => crate::motion_names::motioncommand(name),
        "VendorType" => vendortype(name),
        "PlayScript" => crate::motion_names::playscript(name),
        "Sound" => crate::motion_names::sound(name),
        "RegenerationType" => regenerationtype(name),
        "RegenLocationType" => regenlocationtype(name),
        "SkillAdvancementClass" => skilladvancementclass(name),
        "EmoteType" => emotetype(name),
        _ => None,
    }
}

fn weenietype(name: &str) -> Option<u32> {
    match name {
        "Undef" => Some(0),
        "Generic" => Some(1),
        "Clothing" => Some(2),
        "MissileLauncher" => Some(3),
        "Missile" => Some(4),
        "Ammunition" => Some(5),
        "MeleeWeapon" => Some(6),
        "Portal" => Some(7),
        "Book" => Some(8),
        "Coin" => Some(9),
        "Creature" => Some(10),
        "Admin" => Some(11),
        "Vendor" => Some(12),
        "HotSpot" => Some(13),
        "Corpse" => Some(14),
        "Cow" => Some(15),
        "AI" => Some(16),
        "Machine" => Some(17),
        "Food" => Some(18),
        "Door" => Some(19),
        "Chest" => Some(20),
        "Container" => Some(21),
        "Key" => Some(22),
        "Lockpick" => Some(23),
        "PressurePlate" => Some(24),
        "LifeStone" => Some(25),
        "Switch" => Some(26),
        "PKModifier" => Some(27),
        "Healer" => Some(28),
        "LightSource" => Some(29),
        "Allegiance" => Some(30),
        "UNKNOWN__GUESSEDNAME32" => Some(31),
        "SpellComponent" => Some(32),
        "ProjectileSpell" => Some(33),
        "Scroll" => Some(34),
        "Caster" => Some(35),
        "Channel" => Some(36),
        "ManaStone" => Some(37),
        "Gem" => Some(38),
        "AdvocateFane" => Some(39),
        "AdvocateItem" => Some(40),
        "Sentinel" => Some(41),
        "GSpellEconomy" => Some(42),
        "LSpellEconomy" => Some(43),
        "CraftTool" => Some(44),
        "LScoreKeeper" => Some(45),
        "GScoreKeeper" => Some(46),
        "GScoreGatherer" => Some(47),
        "ScoreBook" => Some(48),
        "EventCoordinator" => Some(49),
        "Entity" => Some(50),
        "Stackable" => Some(51),
        "HUD" => Some(52),
        "House" => Some(53),
        "Deed" => Some(54),
        "SlumLord" => Some(55),
        "Hook" => Some(56),
        "Storage" => Some(57),
        "BootSpot" => Some(58),
        "HousePortal" => Some(59),
        "Game" => Some(60),
        "GamePiece" => Some(61),
        "SkillAlterationDevice" => Some(62),
        "AttributeTransferDevice" => Some(63),
        "Hooker" => Some(64),
        "AllegianceBindstone" => Some(65),
        "InGameStatKeeper" => Some(66),
        "AugmentationDevice" => Some(67),
        "SocialManager" => Some(68),
        "Pet" => Some(69),
        "PetDevice" => Some(70),
        "CombatPet" => Some(71),
        _ => None,
    }
}

fn damagetype(name: &str) -> Option<u32> {
    match name {
        "Undef" => Some(0),
        "Slash" => Some(1),
        "Pierce" => Some(2),
        "Bludgeon" => Some(4),
        "Cold" => Some(8),
        "Fire" => Some(16),
        "Acid" => Some(32),
        "Electric" => Some(64),
        "Health" => Some(128),
        "Stamina" => Some(256),
        "Mana" => Some(512),
        "Nether" => Some(1024),
        "Base" => Some(268435456),
        "Physical" => Some(7),
        "Elemental" => Some(120),
        _ => None,
    }
}

fn destinationtype(name: &str) -> Option<u32> {
    match name {
        "Undef" => Some(0),
        "Contain" => Some(1),
        "Wield" => Some(2),
        "Shop" => Some(4),
        "Treasure" => Some(8),
        "HouseBuy" => Some(16),
        "HouseRent" => Some(32),
        "Checkpoint" => Some(7),
        "ContainTreasure" => Some(9),
        "WieldTreasure" => Some(10),
        "ShopTreasure" => Some(12),
        _ => None,
    }
}

fn emotecategory(name: &str) -> Option<u32> {
    match name {
        "Invalid" => Some(0),
        "Refuse" => Some(1),
        "Vendor" => Some(2),
        "Death" => Some(3),
        "Portal" => Some(4),
        "HeartBeat" => Some(5),
        "Give" => Some(6),
        "Use" => Some(7),
        "Activation" => Some(8),
        "Generation" => Some(9),
        "PickUp" => Some(10),
        "Drop" => Some(11),
        "QuestSuccess" => Some(12),
        "QuestFailure" => Some(13),
        "Taunt" => Some(14),
        "WoundedTaunt" => Some(15),
        "KillTaunt" => Some(16),
        "NewEnemy" => Some(17),
        "Scream" => Some(18),
        "Homesick" => Some(19),
        "ReceiveCritical" => Some(20),
        "ResistSpell" => Some(21),
        "TestSuccess" => Some(22),
        "TestFailure" => Some(23),
        "HearChat" => Some(24),
        "Wield" => Some(25),
        "UnWield" => Some(26),
        "EventSuccess" => Some(27),
        "EventFailure" => Some(28),
        "TestNoQuality" => Some(29),
        "QuestNoFellow" => Some(30),
        "TestNoFellow" => Some(31),
        "GotoSet" => Some(32),
        "NumFellowsSuccess" => Some(33),
        "NumFellowsFailure" => Some(34),
        "NumCharacterTitlesSuccess" => Some(35),
        "NumCharacterTitlesFailure" => Some(36),
        "ReceiveLocalSignal" => Some(37),
        "ReceiveTalkDirect" => Some(38),
        _ => None,
    }
}

fn vendortype(name: &str) -> Option<u32> {
    match name {
        "Undef" => Some(0),
        "Open" => Some(1),
        "Close" => Some(2),
        "Sell" => Some(3),
        "Buy" => Some(4),
        "Heartbeat" => Some(5),
        _ => None,
    }
}

fn regenerationtype(name: &str) -> Option<u32> {
    match name {
        "Undef" => Some(0),
        "Destruction" => Some(1),
        "PickUp" => Some(2),
        "Death" => Some(4),
        _ => None,
    }
}

fn regenlocationtype(name: &str) -> Option<u32> {
    match name {
        "Undef" => Some(0),
        "OnTop" => Some(1),
        "Scatter" => Some(2),
        "Specific" => Some(4),
        "Contain" => Some(8),
        "Wield" => Some(16),
        "Shop" => Some(32),
        "Treasure" => Some(64),
        "Checkpoint" => Some(56),
        "OnTopTreasure" => Some(65),
        "ScatterTreasure" => Some(66),
        "SpecificTreasure" => Some(68),
        "ContainTreasure" => Some(72),
        "WieldTreasure" => Some(80),
        "ShopTreasure" => Some(96),
        _ => None,
    }
}

fn skilladvancementclass(name: &str) -> Option<u32> {
    match name {
        "Inactive" => Some(0),
        "Untrained" => Some(1),
        "Trained" => Some(2),
        "Specialized" => Some(3),
        _ => None,
    }
}

fn emotetype(name: &str) -> Option<u32> {
    match name {
        "Invalid" => Some(0),
        "InvalidVendor" => Some(0),
        "Act" => Some(1),
        "AwardXP" => Some(2),
        "Give" => Some(3),
        "MoveHome" => Some(4),
        "Motion" => Some(5),
        "Move" => Some(6),
        "PhysScript" => Some(7),
        "Say" => Some(8),
        "Sound" => Some(9),
        "Tell" => Some(10),
        "Turn" => Some(11),
        "TurnToTarget" => Some(12),
        "TextDirect" => Some(13),
        "CastSpell" => Some(14),
        "Activate" => Some(15),
        "WorldBroadcast" => Some(16),
        "LocalBroadcast" => Some(17),
        "DirectBroadcast" => Some(18),
        "CastSpellInstant" => Some(19),
        "UpdateQuest" => Some(20),
        "InqQuest" => Some(21),
        "StampQuest" => Some(22),
        "StartEvent" => Some(23),
        "StopEvent" => Some(24),
        "BLog" => Some(25),
        "AdminSpam" => Some(26),
        "TeachSpell" => Some(27),
        "AwardSkillXP" => Some(28),
        "AwardSkillPoints" => Some(29),
        "InqQuestSolves" => Some(30),
        "EraseQuest" => Some(31),
        "DecrementQuest" => Some(32),
        "IncrementQuest" => Some(33),
        "AddCharacterTitle" => Some(34),
        "InqBoolStat" => Some(35),
        "InqIntStat" => Some(36),
        "InqFloatStat" => Some(37),
        "InqStringStat" => Some(38),
        "InqAttributeStat" => Some(39),
        "InqRawAttributeStat" => Some(40),
        "InqSecondaryAttributeStat" => Some(41),
        "InqRawSecondaryAttributeStat" => Some(42),
        "InqSkillStat" => Some(43),
        "InqRawSkillStat" => Some(44),
        "InqSkillTrained" => Some(45),
        "InqSkillSpecialized" => Some(46),
        "AwardTrainingCredits" => Some(47),
        "InflictVitaePenalty" => Some(48),
        "AwardLevelProportionalXP" => Some(49),
        "AwardLevelProportionalSkillXP" => Some(50),
        "InqEvent" => Some(51),
        "ForceMotion" => Some(52),
        "SetIntStat" => Some(53),
        "IncrementIntStat" => Some(54),
        "DecrementIntStat" => Some(55),
        "CreateTreasure" => Some(56),
        "ResetHomePosition" => Some(57),
        "InqFellowQuest" => Some(58),
        "InqFellowNum" => Some(59),
        "UpdateFellowQuest" => Some(60),
        "StampFellowQuest" => Some(61),
        "AwardNoShareXP" => Some(62),
        "SetSanctuaryPosition" => Some(63),
        "TellFellow" => Some(64),
        "FellowBroadcast" => Some(65),
        "LockFellow" => Some(66),
        "Goto" => Some(67),
        "PopUp" => Some(68),
        "SetBoolStat" => Some(69),
        "SetQuestCompletions" => Some(70),
        "InqNumCharacterTitles" => Some(71),
        "Generate" => Some(72),
        "PetCastSpellOnOwner" => Some(73),
        "TakeItems" => Some(74),
        "InqYesNo" => Some(75),
        "InqOwnsItems" => Some(76),
        "DeleteSelf" => Some(77),
        "KillSelf" => Some(78),
        "UpdateMyQuest" => Some(79),
        "InqMyQuest" => Some(80),
        "StampMyQuest" => Some(81),
        "InqMyQuestSolves" => Some(82),
        "EraseMyQuest" => Some(83),
        "DecrementMyQuest" => Some(84),
        "IncrementMyQuest" => Some(85),
        "SetMyQuestCompletions" => Some(86),
        "MoveToPos" => Some(87),
        "LocalSignal" => Some(88),
        "InqPackSpace" => Some(89),
        "RemoveVitaePenalty" => Some(90),
        "SetEyeTexture" => Some(91),
        "SetEyePalette" => Some(92),
        "SetNoseTexture" => Some(93),
        "SetNosePalette" => Some(94),
        "SetMouthTexture" => Some(95),
        "SetMouthPalette" => Some(96),
        "SetHeadObject" => Some(97),
        "SetHeadPalette" => Some(98),
        "TeleportTarget" => Some(99),
        "TeleportSelf" => Some(100),
        "StartBarber" => Some(101),
        "InqQuestBitsOn" => Some(102),
        "InqQuestBitsOff" => Some(103),
        "InqMyQuestBitsOn" => Some(104),
        "InqMyQuestBitsOff" => Some(105),
        "SetQuestBitsOn" => Some(106),
        "SetQuestBitsOff" => Some(107),
        "SetMyQuestBitsOn" => Some(108),
        "SetMyQuestBitsOff" => Some(109),
        "UntrainSkill" => Some(110),
        "SetAltRacialSkills" => Some(111),
        "SpendLuminance" => Some(112),
        "AwardLuminance" => Some(113),
        "InqInt64Stat" => Some(114),
        "SetInt64Stat" => Some(115),
        "OpenMe" => Some(116),
        "CloseMe" => Some(117),
        "SetFloatStat" => Some(118),
        "AddContract" => Some(119),
        "RemoveContract" => Some(120),
        "InqContractsFull" => Some(121),
        "Enlightenment" => Some(9001),
        _ => None,
    }
}
