//! Exact field-name mapping for pinned ACE.Entity.Models JSON; AGPL-3.0-only.
const FIELDS: &[(&str, &str)] = &[
    ("Amount", "amount"),
    ("Amount64", "amount64"),
    ("AnglesW", "angles_w"),
    ("AnglesX", "angles_x"),
    ("AnglesY", "angles_y"),
    ("AnglesZ", "angles_z"),
    ("AnimationId", "animation_id"),
    ("ApprovedVassal", "approved_vassal"),
    ("ArmorVsAcid", "armor_vs_acid"),
    ("ArmorVsBludgeon", "armor_vs_bludgeon"),
    ("ArmorVsCold", "armor_vs_cold"),
    ("ArmorVsElectric", "armor_vs_electric"),
    ("ArmorVsFire", "armor_vs_fire"),
    ("ArmorVsNether", "armor_vs_nether"),
    ("ArmorVsPierce", "armor_vs_pierce"),
    ("ArmorVsSlash", "armor_vs_slash"),
    ("AuthorAccount", "author_account"),
    ("AuthorId", "author_id"),
    ("AuthorName", "author_name"),
    ("BH", "bh"),
    ("Banned", "banned"),
    ("BaseArmor", "base_armor"),
    ("CPSpent", "cp_spent"),
    ("CasterObjectId", "caster_object_id"),
    ("Category", "category"),
    ("CurrentLevel", "current_level"),
    ("DType", "d_type"),
    ("DVal", "d_val"),
    ("DVar", "d_var"),
    ("DatabaseRecordId", "database_record_id"),
    ("DegradeLimit", "degrade_limit"),
    ("DegradeModifier", "degrade_modifier"),
    ("Delay", "delay"),
    ("DestinationType", "destination_type"),
    ("Display", "display"),
    ("Duration", "duration"),
    ("EnchantmentCategory", "enchantment_category"),
    ("Extent", "extent"),
    ("HLB", "hlb"),
    ("HLF", "hlf"),
    ("HRB", "hrb"),
    ("HRF", "hrf"),
    ("HasSpellSetId", "has_spell_set_id"),
    ("HeroXP64", "hero_xp64"),
    ("IgnoreAuthor", "ignore_author"),
    ("Index", "index"),
    ("InitCreate", "init_create"),
    ("InitLevel", "init_level"),
    ("LLB", "llb"),
    ("LLF", "llf"),
    ("LRB", "lrb"),
    ("LRF", "lrf"),
    ("LastTimeDegraded", "last_time_degraded"),
    ("LastUsedTime", "last_used_time"),
    ("LayerId", "layer_id"),
    ("Length", "length"),
    ("LevelFromCP", "level_from_cp"),
    ("LevelFromPP", "level_from_pp"),
    ("MLB", "mlb"),
    ("MLF", "mlf"),
    ("MRB", "mrb"),
    ("MRF", "mrf"),
    ("Max", "max"),
    ("Max64", "max64"),
    ("MaxCreate", "max_create"),
    ("MaxDbl", "max_dbl"),
    ("MaxHealth", "max_health"),
    ("MaxNumCharsPerPage", "max_num_chars_per_page"),
    ("MaxNumPages", "max_num_pages"),
    ("Message", "message"),
    ("Min", "min"),
    ("Min64", "min64"),
    ("MinDbl", "min_dbl"),
    ("MinHealth", "min_health"),
    ("Motion", "motion"),
    ("NewTexture", "new_texture"),
    ("ObjCellId", "obj_cell_id"),
    ("Offset", "offset"),
    ("OldTexture", "old_texture"),
    ("OriginX", "origin_x"),
    ("OriginY", "origin_y"),
    ("OriginZ", "origin_z"),
    ("PP", "pp"),
    ("PScript", "p_script"),
    ("PageText", "page_text"),
    ("Palette", "palette"),
    ("PaletteId", "palette_id"),
    ("PartIndex", "part_index"),
    ("Percent", "percent"),
    ("PositionX", "position_x"),
    ("PositionY", "position_y"),
    ("PositionZ", "position_z"),
    ("PowerLevel", "power_level"),
    ("Probability", "probability"),
    ("PropertiesEmoteAction", "actions"),
    ("Quest", "quest"),
    ("ResistanceAtLastCheck", "resistance_at_last_check"),
    ("RotationW", "rotation_w"),
    ("RotationX", "rotation_x"),
    ("RotationY", "rotation_y"),
    ("RotationZ", "rotation_z"),
    ("SAC", "sac"),
    ("Shade", "shade"),
    ("Sound", "sound"),
    ("SpellCategory", "spell_category"),
    ("SpellId", "spell_id"),
    ("SpellSetId", "spell_set_id"),
    ("StackSize", "stack_size"),
    ("StartTime", "start_time"),
    ("Stat", "stat"),
    ("StatModKey", "stat_mod_key"),
    ("StatModType", "stat_mod_type"),
    ("StatModValue", "stat_mod_value"),
    ("Style", "style"),
    ("SubPaletteId", "sub_palette_id"),
    ("Substyle", "substyle"),
    ("TestString", "test_string"),
    ("TreasureClass", "treasure_class"),
    ("TreasureType", "treasure_type"),
    ("TryToBond", "try_to_bond"),
    ("Type", "type"),
    ("VendorType", "vendor_type"),
    ("WealthRating", "wealth_rating"),
    ("WeenieClassId", "weenie_class_id"),
    ("WhenCreate", "when_create"),
    ("WhereCreate", "where_create"),
];

pub(crate) fn field(name: &str) -> Option<&'static str> {
    FIELDS
        .iter()
        .find(|(legacy, _)| *legacy == name)
        .map(|(_, native)| *native)
}

pub(crate) fn legacy(name: &str) -> Option<&'static str> {
    FIELDS
        .iter()
        .find(|(_, native)| *native == name)
        .map(|(legacy, _)| *legacy)
}
