//! Fixed extraction mapping from pinned official WorldBase.sql; data SQL is
//! executed by MariaDB, never translated or regex-parsed by this importer.
pub(crate) struct TableSpec {
    pub name: &'static str,
    pub native: &'static str,
    pub key: &'static str,
    pub order: &'static str,
    pub fields: &'static [(&'static str, &'static str)],
}

pub(crate) const TABLES: &[TableSpec] = &[
    TableSpec {
        name: "weenie",
        native: "",
        key: "",
        order: "class_Id",
        fields: &[
            ("class_Id", "weenie_id"),
            ("class_Name", "class_name"),
            ("type", "weenie_type"),
            ("last_Modified", "last_modified"),
        ],
    },
    TableSpec {
        name: "weenie_properties_anim_part",
        native: "animation_parts",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("index", "index"),
            ("animation_Id", "animation_id"),
        ],
    },
    TableSpec {
        name: "weenie_properties_attribute",
        native: "attributes",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("init_Level", "init_level"),
            ("level_From_C_P", "level_from_cp"),
            ("c_P_Spent", "cp_spent"),
        ],
    },
    TableSpec {
        name: "weenie_properties_attribute_2nd",
        native: "secondary_attributes",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("init_Level", "init_level"),
            ("level_From_C_P", "level_from_cp"),
            ("c_P_Spent", "cp_spent"),
            ("current_Level", "current_level"),
        ],
    },
    TableSpec {
        name: "weenie_properties_body_part",
        native: "body_parts",
        key: "key",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("key", "key"),
            ("d_Type", "d_type"),
            ("d_Val", "d_val"),
            ("d_Var", "d_var"),
            ("base_Armor", "base_armor"),
            ("armor_Vs_Slash", "armor_vs_slash"),
            ("armor_Vs_Pierce", "armor_vs_pierce"),
            ("armor_Vs_Bludgeon", "armor_vs_bludgeon"),
            ("armor_Vs_Cold", "armor_vs_cold"),
            ("armor_Vs_Fire", "armor_vs_fire"),
            ("armor_Vs_Acid", "armor_vs_acid"),
            ("armor_Vs_Electric", "armor_vs_electric"),
            ("armor_Vs_Nether", "armor_vs_nether"),
            ("b_h", "bh"),
            ("h_l_f", "hlf"),
            ("m_l_f", "mlf"),
            ("l_l_f", "llf"),
            ("h_r_f", "hrf"),
            ("m_r_f", "mrf"),
            ("l_r_f", "lrf"),
            ("h_l_b", "hlb"),
            ("m_l_b", "mlb"),
            ("l_l_b", "llb"),
            ("h_r_b", "hrb"),
            ("m_r_b", "mrb"),
            ("l_r_b", "lrb"),
        ],
    },
    TableSpec {
        name: "weenie_properties_book",
        native: "book",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("max_Num_Pages", "max_num_pages"),
            ("max_Num_Chars_Per_Page", "max_num_chars_per_page"),
        ],
    },
    TableSpec {
        name: "weenie_properties_book_page_data",
        native: "book_pages",
        key: "",
        order: "object_Id,page_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("page_Id", "legacy_page_id"),
            ("author_Id", "author_id"),
            ("author_Name", "author_name"),
            ("author_Account", "author_account"),
            ("ignore_Author", "ignore_author"),
            ("page_Text", "page_text"),
        ],
    },
    TableSpec {
        name: "weenie_properties_bool",
        native: "bools",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("value", "value"),
        ],
    },
    TableSpec {
        name: "weenie_properties_create_list",
        native: "create_list",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("destination_Type", "destination_type"),
            ("weenie_Class_Id", "weenie_class_id"),
            ("stack_Size", "stack_size"),
            ("palette", "palette"),
            ("shade", "shade"),
            ("try_To_Bond", "try_to_bond"),
        ],
    },
    TableSpec {
        name: "weenie_properties_d_i_d",
        native: "data_ids",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("value", "value"),
        ],
    },
    TableSpec {
        name: "weenie_properties_emote",
        native: "emotes",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("category", "category"),
            ("probability", "probability"),
            ("weenie_Class_Id", "weenie_class_id"),
            ("style", "style"),
            ("substyle", "substyle"),
            ("quest", "quest"),
            ("vendor_Type", "vendor_type"),
            ("min_Health", "min_health"),
            ("max_Health", "max_health"),
        ],
    },
    TableSpec {
        name: "weenie_properties_emote_action",
        native: "actions",
        key: "",
        order: "emote_Id,order,id",
        fields: &[
            ("id", "database_record_id"),
            ("emote_Id", "emote_id"),
            ("order", "legacy_order"),
            ("type", "type"),
            ("delay", "delay"),
            ("extent", "extent"),
            ("motion", "motion"),
            ("message", "message"),
            ("test_String", "test_string"),
            ("min", "min"),
            ("max", "max"),
            ("min_64", "min64"),
            ("max_64", "max64"),
            ("min_Dbl", "min_dbl"),
            ("max_Dbl", "max_dbl"),
            ("stat", "stat"),
            ("display", "display"),
            ("amount", "amount"),
            ("amount_64", "amount64"),
            ("hero_X_P_64", "hero_xp64"),
            ("percent", "percent"),
            ("spell_Id", "spell_id"),
            ("wealth_Rating", "wealth_rating"),
            ("treasure_Class", "treasure_class"),
            ("treasure_Type", "treasure_type"),
            ("p_Script", "p_script"),
            ("sound", "sound"),
            ("destination_Type", "destination_type"),
            ("weenie_Class_Id", "weenie_class_id"),
            ("stack_Size", "stack_size"),
            ("palette", "palette"),
            ("shade", "shade"),
            ("try_To_Bond", "try_to_bond"),
            ("obj_Cell_Id", "obj_cell_id"),
            ("origin_X", "origin_x"),
            ("origin_Y", "origin_y"),
            ("origin_Z", "origin_z"),
            ("angles_W", "angles_w"),
            ("angles_X", "angles_x"),
            ("angles_Y", "angles_y"),
            ("angles_Z", "angles_z"),
        ],
    },
    TableSpec {
        name: "weenie_properties_event_filter",
        native: "event_filter",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("event", "event"),
        ],
    },
    TableSpec {
        name: "weenie_properties_float",
        native: "floats",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("value", "value"),
        ],
    },
    TableSpec {
        name: "weenie_properties_generator",
        native: "generators",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("probability", "probability"),
            ("weenie_Class_Id", "weenie_class_id"),
            ("delay", "delay"),
            ("init_Create", "init_create"),
            ("max_Create", "max_create"),
            ("when_Create", "when_create"),
            ("where_Create", "where_create"),
            ("stack_Size", "stack_size"),
            ("palette_Id", "palette_id"),
            ("shade", "shade"),
            ("obj_Cell_Id", "obj_cell_id"),
            ("origin_X", "origin_x"),
            ("origin_Y", "origin_y"),
            ("origin_Z", "origin_z"),
            ("angles_W", "angles_w"),
            ("angles_X", "angles_x"),
            ("angles_Y", "angles_y"),
            ("angles_Z", "angles_z"),
        ],
    },
    TableSpec {
        name: "weenie_properties_i_i_d",
        native: "instance_ids",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("value", "value"),
        ],
    },
    TableSpec {
        name: "weenie_properties_int",
        native: "ints",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("value", "value"),
        ],
    },
    TableSpec {
        name: "weenie_properties_int64",
        native: "int64s",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("value", "value"),
        ],
    },
    TableSpec {
        name: "weenie_properties_palette",
        native: "palettes",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("sub_Palette_Id", "sub_palette_id"),
            ("offset", "offset"),
            ("length", "length"),
        ],
    },
    TableSpec {
        name: "weenie_properties_position",
        native: "positions",
        key: "position_Type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("position_Type", "position_type"),
            ("obj_Cell_Id", "obj_cell_id"),
            ("origin_X", "position_x"),
            ("origin_Y", "position_y"),
            ("origin_Z", "position_z"),
            ("angles_W", "rotation_w"),
            ("angles_X", "rotation_x"),
            ("angles_Y", "rotation_y"),
            ("angles_Z", "rotation_z"),
        ],
    },
    TableSpec {
        name: "weenie_properties_skill",
        native: "skills",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("level_From_P_P", "level_from_pp"),
            ("s_a_c", "sac"),
            ("p_p", "pp"),
            ("init_Level", "init_level"),
            ("resistance_At_Last_Check", "resistance_at_last_check"),
            ("last_Used_Time", "last_used_time"),
        ],
    },
    TableSpec {
        name: "weenie_properties_spell_book",
        native: "spell_book",
        key: "spell",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("spell", "spell"),
            ("probability", "probability"),
        ],
    },
    TableSpec {
        name: "weenie_properties_string",
        native: "strings",
        key: "type",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("type", "type"),
            ("value", "value"),
        ],
    },
    TableSpec {
        name: "weenie_properties_texture_map",
        native: "texture_maps",
        key: "",
        order: "object_Id,id",
        fields: &[
            ("id", "database_record_id"),
            ("object_Id", "object_id"),
            ("index", "part_index"),
            ("old_Id", "old_texture"),
            ("new_Id", "new_texture"),
        ],
    },
];
