using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Text.Json;
using ACE.DatLoader;
using ACE.DatLoader.Entity;
using ACE.DatLoader.FileTypes;
using ACE.Entity.Enum;
// Unused dependency of Frame's convenience constructor, not any decoder.
namespace ACE.Entity { public class Position { public System.Numerics.Vector3 Pos; public System.Numerics.Quaternion Rotation; public float PositionX,PositionY,PositionZ,RotationW,RotationX,RotationY,RotationZ; } }
namespace ACE.DatLoader { public static class DatManager {public static StubDatabase PortalDat=new StubDatabase();} public class StubDatabase {public T ReadFromDat<T>(uint id) where T:FileType,new()=>throw new Exception("unused");} }
namespace log4net { public interface ILog {void Warn(object value);} public static class LogManager {private class Log:ILog {public void Warn(object value){throw new Exception("unexpected unknown oracle hook");}} public static ILog GetLogger(Type t)=>new Log();} }
class Program {
 static byte[] Make(Action<BinaryWriter> action) {using var s=new MemoryStream();using var w=new BinaryWriter(s);action(w);return s.ToArray();}
 static void Floats(BinaryWriter w,params float[] v){foreach(var x in v)w.Write(x);}
 static void Frame(BinaryWriter w){Floats(w,1.25f,-2,3,0.5f,-0.5f,0.5f,-0.5f);}
 static object FrameValue(ACE.DatLoader.Entity.Frame f)=>new {origin=new[]{f.Origin.X,f.Origin.Y,f.Origin.Z},rotation=new[]{f.Orientation.W,f.Orientation.X,f.Orientation.Y,f.Orientation.Z}};
 static object Env(bool populated){
  var b=Make(w=>{w.Write(0x12340100u);w.Write(populated?11u:0u);w.Write(0x98760100u);w.Write((byte)(populated?2:0));w.Write((byte)(populated?1:0));w.Write((ushort)(populated?2:0));if(populated){w.Write((ushort)7);w.Write((ushort)0xffff);}w.Write((ushort)8);w.Write((ushort)9);Frame(w);if(populated){foreach(var x in new ushort[]{3,0xffff,0x101,0xfffe,0x102,0x103})w.Write(x);w.Write(1u);w.Write(0x02000007u);Frame(w);w.Write(0x80000123u);}});
  var item=new EnvCell();using var r=new BinaryReader(new MemoryStream(b));item.Unpack(r);if(r.BaseStream.Position!=b.Length)throw new Exception("EnvCell trailing");
  return new {bytes=Convert.ToHexString(b),decoded=new{id=item.Id,flags=(uint)item.Flags,surfaces=item.Surfaces,environment_id=item.EnvironmentId,cell_structure=item.CellStructure,position=FrameValue(item.Position),portals=item.CellPortals.Select(p=>new{flags=(ushort)p.Flags,polygon_id=p.PolygonId,other_cell_id=p.OtherCellId,other_portal_id=p.OtherPortalId}),visible_cells=item.VisibleCells,static_objects=item.StaticObjects.Select(s=>new{id=s.Id,frame=FrameValue(s.Frame)}),restriction_object=populated?(uint?)item.RestrictionObj:null}};
 }
 static uint Tag(string s)=>((uint)s[0]<<24)|((uint)s[1]<<16)|((uint)s[2]<<8)|s[3];
 static void Sphere(BinaryWriter w){Floats(w,1,2,3,4);}
 static void Leaf(BinaryWriter w,BSPType kind,int index){w.Write(Tag("LEAF"));w.Write(index);if(kind==BSPType.Physics){w.Write(-1);Sphere(w);w.Write(2u);w.Write((ushort)4);w.Write((ushort)0xffff);}}
 static object Bsp(BSPType kind,string tag){
  var b=Make(w=>{if(tag=="LEAF"){Leaf(w,kind,-7);return;}w.Write(Tag(tag));Floats(w,1,0,0,-2);if(new[]{"BPnn","BPIn","BPIN","BPnN","PORT"}.Contains(tag))Leaf(w,kind,8);if(new[]{"BpIN","BpnN","BPIN","BPnN","PORT"}.Contains(tag))Leaf(w,kind,-9);if(tag=="PORT"){if(kind==BSPType.Drawing){Sphere(w);w.Write(1u);w.Write(2u);w.Write((ushort)12);w.Write((short)-1);w.Write((short)7);w.Write((short)3);w.Write((short)-8);}}else if(kind!=BSPType.Cell){Sphere(w);if(kind==BSPType.Drawing){w.Write(2u);w.Write((ushort)5);w.Write((ushort)6);}}});
  var item=new BSPTree();using var r=new BinaryReader(new MemoryStream(b));item.Unpack(r,kind);if(r.BaseStream.Position!=b.Length)throw new Exception("BSP trailing");var nodes=new List<object>();Walk(item.RootNode,nodes,kind);
  return new{kind=(int)kind,tag,bytes=Convert.ToHexString(b),nodes};
 }
 static int Walk(BSPNode n,List<object> nodes,BSPType kind){int index=nodes.Count;nodes.Add(null);int? positive=n.PosNode==null?null:Walk(n.PosNode,nodes,kind);int? negative=n.NegNode==null?null:Walk(n.NegNode,nodes,kind);nodes[index]=new{tag=Tag(n.Type),positive,negative,splitting_plane=n.SplittingPlane==null?null:new[]{n.SplittingPlane.N.X,n.SplittingPlane.N.Y,n.SplittingPlane.N.Z,n.SplittingPlane.D},sphere=n.Sphere==null?null:new{origin=new[]{n.Sphere.Origin.X,n.Sphere.Origin.Y,n.Sphere.Origin.Z},radius=n.Sphere.Radius},polygons=n.InPolys??new List<ushort>(),portal_polygons=n is BSPPortal p?p.InPortals.Select(x=>new[]{x.PortalIndex,x.PolygonId}).ToArray():Array.Empty<short[]>(),leaf_index=n is BSPLeaf l?(int?)l.LeafIndex:null,solid=n is BSPLeaf ll&&kind==BSPType.Physics?(int?)ll.Solid:null};return index;}

 static void Data(BinaryWriter w,byte flags){w.Write((byte)1);w.Write((byte)0x81);w.Write(flags);while(w.BaseStream.Position%4!=0)w.Write((byte)0xCC);w.Write(0x03000001u);w.Write(-2);w.Write(-1);w.Write(-30.5f);if((flags&1)!=0)Floats(w,1,2,3);if((flags&2)!=0)Floats(w,4,5,6);}
 static object DataValue(MotionData d)=>new{bitfield=d.Bitfield,flags=(byte)d.Flags,animations=d.Anims.Select(a=>new{animation_id=a.AnimId,low_frame=a.LowFrame,high_frame=a.HighFrame,framerate=a.Framerate}),velocity=d.Flags.HasFlag(MotionDataFlags.HasVelocity)?new[]{d.Velocity.X,d.Velocity.Y,d.Velocity.Z}:null,omega=d.Flags.HasFlag(MotionDataFlags.HasOmega)?new[]{d.Omega.X,d.Omega.Y,d.Omega.Z}:null};
 static object Motion(){var b=Make(w=>{w.Write(0x09000001u);w.Write(0x8000003du);w.Write(2u);w.Write(0x8000003du);w.Write(0x40000003u);w.Write(7u);w.Write(9u);w.Write(1u);w.Write(0x003d0003u);Data(w,3);w.Write(1u);w.Write(0x1234u);Data(w,1);w.Write(1u);w.Write(0x8000003du);w.Write(2u);w.Write(0x40000004u);Data(w,2);w.Write(0x40000005u);Data(w,0);});var m=new MotionTable();using var r=new BinaryReader(new MemoryStream(b));m.Unpack(r);if(r.BaseStream.Position!=b.Length)throw new Exception("motion trailing");return new{bytes=Convert.ToHexString(b),decoded=new{id=m.Id,default_style=m.DefaultStyle,style_defaults=m.StyleDefaults,cycles=m.Cycles.ToDictionary(x=>x.Key,x=>DataValue(x.Value)),modifiers=m.Modifiers.ToDictionary(x=>x.Key,x=>DataValue(x.Value)),links=m.Links.ToDictionary(x=>x.Key,x=>x.Value.ToDictionary(y=>y.Key,y=>DataValue(y.Value)))}};}
 static void Hook(BinaryWriter w,uint kind){w.Write(kind);w.Write(-1);switch(kind){case 4:case 17:break;case 1:case 2:case 6:case 14:case 15:case 16:case 18:case 25:w.Write(0x80000001u);break;case 3:w.Write(7u);Floats(w,1,2,3,4,5,6);break;case 5:w.Write((ushort)0x1234);w.Write((ushort)0x8001);w.Write((ushort)0x2345);break;case 7:case 9:case 11:w.Write(8u);Floats(w,1,2,3);break;case 8:case 10:case 20:case 22:Floats(w,1,2,3);break;case 12:case 23:Floats(w,1,2);break;case 13:case 26:w.Write(0x32000001u);w.Write(9u);Frame(w);w.Write(10u);break;case 19:w.Write(0x33000001u);w.Write(2.5f);break;case 21:w.Write(0x20000001u);Floats(w,1,0.5f,0.75f);break;case 24:w.Write(3u);Floats(w,1,2);break;default:throw new Exception("hook builder");}}
 static object Anim(){var b=Make(w=>{w.Write(0x03000001u);w.Write(1u);w.Write(1u);w.Write(2u);Frame(w);Frame(w);Frame(w);w.Write(26u);for(uint k=1;k<=26;k++)Hook(w,k);Frame(w);w.Write(1u);Hook(w,3);});var a=new Animation();using var r=new BinaryReader(new MemoryStream(b));a.Unpack(r);if(r.BaseStream.Position!=b.Length)throw new Exception("animation trailing");var options=new JsonSerializerOptions{IncludeFields=true};return new{bytes=Convert.ToHexString(b),decoded=new{id=a.Id,flags=(uint)a.Flags,num_parts=a.NumParts,num_frames=a.NumFrames,position_frames=a.PosFrames.Select(FrameValue),frames=a.PartFrames.Select(f=>new{parts=f.Frames.Select(FrameValue),hooks=f.Hooks.Select(h=>JsonSerializer.SerializeToElement(h,h.GetType(),options))})}};}

 static void Align(BinaryWriter w){while(w.BaseStream.Position%4!=0)w.Write((byte)0xCC);}
 static void Polygon(BinaryWriter w,ushort key,int cull){w.Write(key);w.Write((byte)3);w.Write((byte)0);w.Write(cull);w.Write((short)0);w.Write((short)1);foreach(short id in new short[]{0,1,2})w.Write(id);w.Write(new byte[3]);if(cull==2)w.Write(new byte[3]);}
 static object PolyValue(Polygon p)=>new{vertices=p.VertexIds.Select(x=>(ushort)x),positive_uvs=p.PosUVIndices,negative_uvs=p.NegUVIndices,positive_surface=p.PosSurface,negative_surface=p.NegSurface,cull=(uint)p.SidesType,stippling=(byte)p.Stippling};
 static object TreeValue(BSPTree tree,BSPType kind){var nodes=new List<object>();Walk(tree.RootNode,nodes,kind);return nodes;}
 static object Environment(){var b=Make(w=>{w.Write(0x0D000007u);w.Write(2u);for(uint cell=1;cell<=2;cell++){w.Write(cell);w.Write(1u);w.Write(1u);w.Write(1u);w.Write(1);w.Write(3u);for(ushort v=0;v<3;v++){w.Write(v);w.Write((ushort)1);Floats(w,v,-v,0,0,0,1,0.25f,0.75f);}Polygon(w,5,2);w.Write((ushort)5);Align(w);w.Write(Tag("PORT"));Floats(w,1,0,0,-2);Leaf(w,BSPType.Cell,1);Leaf(w,BSPType.Cell,2);Polygon(w,4,1);w.Write(Tag("LEAF"));w.Write(-7);w.Write(1);Sphere(w);w.Write(1u);w.Write((ushort)4);w.Write(cell==1?1u:0u);if(cell==1)Leaf(w,BSPType.Drawing,9);Align(w);}});var e=new ACE.DatLoader.FileTypes.Environment();using var r=new BinaryReader(new MemoryStream(b));e.Unpack(r);if(r.BaseStream.Position!=b.Length)throw new Exception("environment trailing");return new{bytes=Convert.ToHexString(b),id=e.Id,cells=e.Cells.ToDictionary(x=>x.Key,x=>new{vertices=x.Value.VertexArray.Vertices.ToDictionary(v=>v.Key,v=>new{position=new[]{v.Value.Origin.X,v.Value.Origin.Y,v.Value.Origin.Z},normal=new[]{v.Value.Normal.X,v.Value.Normal.Y,v.Value.Normal.Z},uvs=v.Value.UVs.Select(uv=>new[]{uv.U,uv.V})}),polygons=x.Value.Polygons.ToDictionary(p=>p.Key,p=>PolyValue(p.Value)),portals=x.Value.Portals,cell_bsp=TreeValue(x.Value.CellBSP,BSPType.Cell),physics_polygons=x.Value.PhysicsPolygons.ToDictionary(p=>p.Key,p=>PolyValue(p.Value)),physics_bsp=TreeValue(x.Value.PhysicsBSP,BSPType.Physics),drawing_bsp=x.Value.DrawingBSP==null?null:TreeValue(x.Value.DrawingBSP,BSPType.Drawing)})};}

 static object SphereValue(Sphere s)=>new{origin=new[]{s.Origin.X,s.Origin.Y,s.Origin.Z},radius=s.Radius};
 static object Setup(){var b=Make(w=>{w.Write(0x02000001u);w.Write(15u);w.Write(2u);w.Write(0x01000001u);w.Write(0x01000002u);w.Write(0xffffffffu);w.Write(0u);Floats(w,1,1,1,2,2,2);for(int i=0;i<2;i++){w.Write(1u);w.Write(-7-i);w.Write(1);Frame(w);}w.Write(1);w.Write(0);Frame(w);Frame(w);w.Write(1u);Hook(w,6);w.Write(1u);Floats(w,1,2,3,.5f,2.5f);w.Write(2u);Sphere(w);Floats(w,-1,-2,-3,.25f);Floats(w,2.5f,.5f,.4f,.6f);Sphere(w);Sphere(w);w.Write(1u);w.Write(-4);Frame(w);w.Write(0xff112233u);Floats(w,1,.5f,2);foreach(uint v in new uint[]{0x03000001,0x33000001,0x09000001,0x20000001,0x34000001})w.Write(v);});var setup=new SetupModel();using var r=new BinaryReader(new MemoryStream(b));setup.Unpack(r);if(r.BaseStream.Position!=b.Length)throw new Exception("setup trailing");return new{bytes=Convert.ToHexString(b),decoded=new{id=setup.Id,flags=(uint)setup.Flags,parts=setup.Parts,parents=setup.ParentIndex,default_scales=setup.DefaultScale.Select(v=>new[]{v.X,v.Y,v.Z}),holding_locations=setup.HoldingLocations.ToDictionary(x=>x.Key,x=>new{part_id=x.Value.PartId,frame=FrameValue(x.Value.Frame)}),connection_points=setup.ConnectionPoints.ToDictionary(x=>x.Key,x=>new{part_id=x.Value.PartId,frame=FrameValue(x.Value.Frame)}),placements=setup.PlacementFrames.ToDictionary(x=>x.Key,x=>new{parts=x.Value.AnimFrame.Frames.Select(FrameValue),hooks=x.Value.AnimFrame.Hooks.Select(h=>JsonSerializer.SerializeToElement(h,h.GetType()))}),cylinders=setup.CylSpheres.Select(c=>new{origin=new[]{c.Origin.X,c.Origin.Y,c.Origin.Z},radius=c.Radius,height=c.Height}),spheres=setup.Spheres.Select(SphereValue),height=setup.Height,radius=setup.Radius,step_up_height=setup.StepUpHeight,step_down_height=setup.StepDownHeight,sorting_sphere=SphereValue(setup.SortingSphere),selection_sphere=SphereValue(setup.SelectionSphere),lights=setup.Lights.ToDictionary(x=>x.Key,x=>new{frame=FrameValue(x.Value.ViewerSpaceLocation),color=x.Value.Color,intensity=x.Value.Intensity,falloff=x.Value.Falloff,cone_angle=x.Value.ConeAngle}),default_animation=setup.DefaultAnimation,default_script=setup.DefaultScript,default_motion_table=setup.DefaultMotionTable,default_sound_table=setup.DefaultSoundTable,default_script_table=setup.DefaultScriptTable}};}
 static void Main(){var bsps=new List<object>();foreach(BSPType kind in Enum.GetValues<BSPType>())foreach(var tag in new[]{"LEAF","BPnn","BPIn","BpIN","BpnN","BPIN","BPnN","PORT","BpIn","Bpnn","BPOL","BPFL"})bsps.Add(Bsp(kind,tag));Console.WriteLine(JsonSerializer.Serialize(new{env=new[]{Env(false),Env(true)},bsp=bsps,motion=Motion(),animation=Anim(),environment=Environment(),setup=Setup()}));}
}
