//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "accountcreate",
        handler: "HandleAccountCreate",
        source: "Command/Handlers/AccountCommands.cs",
        description: "Creates a new account.",
        usage: "username password (accesslevel)\naccesslevel can be a number or enum name\n0 = Player | 1 = Advocate | 2 = Sentinel | 3 = Envoy | 4 = Developer | 5 = Admin",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "accountget",
        handler: "HandleAccountGet",
        source: "Command/Handlers/AccountCommands.cs",
        description: "Gets an account.",
        usage: "username",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "adminhouse",
        handler: "HandleAdminhouse",
        source: "Command/Handlers/AdminCommands.cs",
        description: "House management tools for admins.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "bornagain",
        handler: "HandleBornAgain",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Restores a deleted character to an account.",
        usage: "deletedCharID(, newCharName)(, accountName)\nGiven the ID of a deleted character, this command restores that character to its owner.  (You can find the ID of a deleted character using the @finger command.)\nIf the deleted character's name has since been taken by a new character, you can specify a new name for the restored character as the second parameter.  (You can find if the name has been taken by also using the @finger command.)  Use a comma to separate the arguments.\nIf needed, you can specify an account name as a third parameter if the character should be restored to an account other than its original owner.  Again, use a comma between the arguments.",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "cancel-shutdown",
        handler: "HandleCancelShutdown",
        source: "Command/Handlers/AdminShardCommands.cs",
        description: "Stops an active server shutdown.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "cell-export",
        handler: "ExportCellDatContents",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Export contents of CELL DAT file.",
        usage: "<export-directory-without-spaces>",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "deletecharacter",
        handler: "HandleCharacterForcedDelete",
        source: "Command/Handlers/CharacterCommands.cs",
        description: "Deletes a character and removes it from players restore list",
        usage: "[character name]\nGiven the name of a character, this command deletes that character, booting it if in game, and removes it from character's restore list.  (You can find the name for a character using the @finger command.)\n",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "exit",
        handler: "Exit",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Shut down server immediately.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fetchbool",
        handler: "HandleFetchServerBoolProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Fetches a server property that is a bool",
        usage: "fetchbool (string)",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fetchdouble",
        handler: "HandleFetchServerFloatProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Fetches a server property that is a double",
        usage: "fetchdouble (string)",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fetchlong",
        handler: "HandleFetchServerLongProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Fetches a server property that is a long",
        usage: "fetchlong (string)",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fetchstring",
        handler: "HandleFetchServerStringProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Fetches a server property that is a string",
        usage: "fetchstring (string)",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fix-allegiances",
        handler: "HandleFixAllegiances",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Fixes the monarch data for allegiances",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fix-biota-emote-delay",
        handler: "HandleFixBiotaEmoteDelay",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Fixes biota emotes with incorrect default delays",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fix-gear-plating",
        handler: "HandleFixGearPlating",
        source: "Command/Handlers/DeveloperDatabaseCommands.cs",
        description: "Corrects the name on Gear Plating.",
        usage: "<execute>",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fix-shortcut-bars",
        handler: "HandleFixShortcutBars",
        source: "Command/Handlers/DeveloperDatabaseCommands.cs",
        description: "Fixes the players with duplicate items on their shortcut bars.",
        usage: "<execute>",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fix-spell-bars",
        handler: "HandleFixSpellBars",
        source: "Command/Handlers/DeveloperDatabaseCommands.cs",
        description: "Fixes the players spell bars.",
        usage: "<execute>",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "getenchantments",
        handler: "HandleGetEnchantments",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Shows the enchantments for the last appraised item",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "highres-export",
        handler: "ExportHighresDatContents",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Export contents of client_highres.dat file.",
        usage: "<export-directory-without-spaces>",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "image-export",
        handler: "ExportImageFile",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Export Texture/Image Files",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "language-export",
        handler: "ExportLanguageDatContents",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Export contents of client_local_English.dat file.",
        usage: "<export-directory-without-spaces>",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "lbinterval",
        handler: "Handlelbinterval",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "lbthresh",
        handler: "Handlelbthresh",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "modifyattr",
        handler: "HandleModifyAttribute",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Adjusts an attribute for the last appraised mob/NPC/player",
        usage: "<attribute> <delta>",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "modifybool",
        handler: "HandleModifyServerBoolProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Modifies a server property that is a bool",
        usage: "modifybool (string) (bool)",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "modifydouble",
        handler: "HandleModifyServerFloatProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Modifies a server property that is a double",
        usage: "modifyfloat (string) (double)",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "modifylong",
        handler: "HandleModifyServerLongProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Modifies a server property that is a long",
        usage: "modifylong (string) (long)",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "modifypropertydesc",
        handler: "HandleModifyPropertyDescription",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Modifies a server property's description",
        usage: "modifypropertydesc <STRING|BOOL|DOUBLE|LONG> (string) (string)",
        access: AccessLevel::Admin,
        min_args: 3,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "modifyskill",
        handler: "HandleModifySkill",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Adjusts the skill for the last appraised mob/player",
        usage: "<skillName> <delta>",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "modifystring",
        handler: "HandleModifyServerStringProperty",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Modifies a server property that is a string",
        usage: "modifystring (string) (string)",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "modifyvital",
        handler: "HandleModifyVital",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Adjusts the maximum vital attribute for the last appraised mob/player and restores full vitals",
        usage: "<Health|Stamina|Mana> <delta>",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "movetome",
        handler: "HandleMoveToMe",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Moves the last appraised object to the current player location.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
