//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "portal-export",
        handler: "ExportPortalDatContents",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Export contents of PORTAL DAT file.",
        usage: "<export-directory-without-spaces>",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "reload-loot-tables",
        handler: "HandleReloadLootTables",
        source: "Command/Handlers/AdminCommands.cs",
        description: "reloads the latest data from the loot tables",
        usage: "optional profile folder",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "resyncproperties",
        handler: "HandleResyncServerProperties",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Resync the properties database",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "set-accountaccess",
        handler: "HandleAccountUpdateAccessLevel",
        source: "Command/Handlers/AccountCommands.cs",
        description: "Change the access level of an account.",
        usage: "accountname (accesslevel)\naccesslevel can be a number or enum name\n0 = Player | 1 = Advocate | 2 = Sentinel | 3 = Envoy | 4 = Developer | 5 = Admin",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "set-accountpassword",
        handler: "HandleAccountSetPassword",
        source: "Command/Handlers/AccountCommands.cs",
        description: "Set the account password.",
        usage: "accountname newpassword\n",
        access: AccessLevel::Admin,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "set-characteraccess",
        handler: "HandleCharacterTokenization",
        source: "Command/Handlers/CharacterCommands.cs",
        description: "Sets the access level for the character",
        usage: "charactername (accesslevel)\naccesslevel can be a number or enum name\n0 = Player | 1 = Advocate | 2 = Sentinel | 3 = Envoy | 4 = Developer | 5 = Admin",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "set-shutdown-interval",
        handler: "HandleSetShutdownInterval",
        source: "Command/Handlers/AdminShardCommands.cs",
        description: "Changes the delay, in seconds, before the server will shutdown.",
        usage: "< 0-99999 > in seconds",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "show-allegiances",
        handler: "HandleShowAllegiances",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Shows all of the allegiance chains on the server.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "showprops",
        handler: "HandleDisplayProps",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Displays the name of all properties configurable via the modify commands",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "shutdown",
        handler: "ShutdownServer",
        source: "Command/Handlers/AdminShardCommands.cs",
        description: "Begins the server shutdown process. Optionally displays a shutdown message, if a string is passed.",
        usage: "< Optional Shutdown Message >\n\tUse @cancel-shutdown to abort an active shutdown!\n\tSet the shutdown delay in seconds with @set-shutdown-interval < 0-99999 >",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "stop-now",
        handler: "ShutdownServerNow",
        source: "Command/Handlers/AdminShardCommands.cs",
        description: "Shuts the server down, immediately!",
        usage: "\nThis command will attempt to safely logoff all players, before shutting down the server.",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "stormnumstormed",
        handler: "Handlestormnumstormed",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "stormthresh",
        handler: "Handlestormthresh",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "testlootgen",
        handler: "TestLootGenerator",
        source: "Command/Handlers/DeveloperLootCommands.cs",
        description: "Generates Loot for testing LootFactories.  Do testlootgen -info for examples.",
        usage: "<number of items> <loot tier> <melee, missile, caster, armor, pet, aetheria (optional)>",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "testlootgencorpse",
        handler: "TestLootGeneratorCorpse",
        source: "Command/Handlers/DeveloperLootCommands.cs",
        description: "Generates Corpses for testing LootFactories",
        usage: "<DID> <number corpses> <display table - melee, missile, caster, armor, pet, aetheria>",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "userlimit",
        handler: "Handleuserlimit",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "verify-armor-levels",
        handler: "HandleFixArmorLevel",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any existing armor levels above AL cap",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-attributes",
        handler: "HandleVerifyAttributes",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any bugs with player attribute data",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-beneficial-enchantments",
        handler: "HandleEnchantments",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies enchantment registry has correct StatModType for Beneficial spells and optionally fixes",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-clothing-wield-level",
        handler: "HandleVerifyClothingWieldLevel",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any t7/t8 clothing that is missing a wield level requirement",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-heritage-augs",
        handler: "HandleVerifyHeritageAugs",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies all players have their heritage augs.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-legendary-wield-level",
        handler: "HandleVerifyLegendaryWieldLevel",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any items with legendary cantrips that have less than 180 wield level requirement",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-max-augs",
        handler: "HandleVerifyMaxAugs",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any bugs with the # of augs each player has",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-melee-rares",
        handler: "HandleFixMeleeRares",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any melee rares to EoR wcids",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-player-data",
        handler: "HandleVerifyAll",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any bugs with player data. Runs all of the verify* commands.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-shield-rating",
        handler: "HandleRemoveShieldRatings",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any lootgen shields with incorrectly assigned CD/CDR",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-skill-credits",
        handler: "HandleVerifySkillCredits",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any bugs with player skill credits",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-skills",
        handler: "HandleVerifySkills",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any bugs with player skill data",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-vitals",
        handler: "HandleVerifyVitals",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any bugs with player vitals data",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "verify-xp",
        handler: "HandleVerifyExperience",
        source: "Command/Handlers/DeveloperFixCommands.cs",
        description: "Verifies and optionally fixes any bugs with player xp",
        usage: "",
        access: AccessLevel::Admin,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "version",
        handler: "ShowVersion",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Show server version information.",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "watchmen",
        handler: "Handlewatchmen",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Displays a list of accounts with the specified level of admin access.",
        usage: "(accesslevel)",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "wave-export",
        handler: "ExportWaveFiles",
        source: "Command/Handlers/ConsoleCommands.cs",
        description: "Export Wave Files",
        usage: "",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "world",
        handler: "HandleHelp",
        source: "Command/Handlers/AdminShardCommands.cs",
        description: "Open or Close world to player access.",
        usage: "[open | close] <boot>\nIf closing world, using @world close boot will force players to logoff immediately",
        access: AccessLevel::Admin,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
];
