//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "allstats",
        handler: "HandleAllStats",
        source: "Command/Handlers/AdminStatCommands.cs",
        description: "Displays a summary of all server statistics and usage",
        usage: "",
        access: AccessLevel::Advocate,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "attackable",
        handler: "HandleAttackable",
        source: "Command/Handlers/AdvocateCommands.cs",
        description: "Sets whether monsters will attack you or not.",
        usage: "[ on | off ]\nThis command sets whether monsters will attack you unprovoked.\n When turned on, monsters will attack you as if you are a normal player.\n When turned off, monsters will ignore you.",
        access: AccessLevel::Advocate,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "bestow",
        handler: "HandleBestow",
        source: "Command/Handlers/AdvocateCommands.cs",
        description: "Sets a character's Advocate Level.",
        usage: "<name> <level>\nAdvocates can bestow any level less than their own.",
        access: AccessLevel::Advocate,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "gcstatus",
        handler: "HandleGCStatus",
        source: "Command/Handlers/AdminStatCommands.cs",
        description: "Displays a summary of server GC Information",
        usage: "",
        access: AccessLevel::Advocate,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "landblockperformance",
        handler: "HandleLandblockStats",
        source: "Command/Handlers/AdminStatCommands.cs",
        description: "Displays a summary of landblock performance statistics",
        usage: "",
        access: AccessLevel::Advocate,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "landblockstats",
        handler: "HandleLandblockStats",
        source: "Command/Handlers/AdminStatCommands.cs",
        description: "Displays a summary of landblock performance statistics",
        usage: "",
        access: AccessLevel::Advocate,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "lbgroupstats",
        handler: "HandleLBGroupStats",
        source: "Command/Handlers/AdminStatCommands.cs",
        description: "Displays a summary of landblock group stats",
        usage: "",
        access: AccessLevel::Advocate,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "remove",
        handler: "HandleRemove",
        source: "Command/Handlers/AdvocateCommands.cs",
        description: "Removes the specified character from the Advocate ranks.",
        usage: "<character name>\nAdvocates can remove Advocate status for any Advocate of lower level than their own.",
        access: AccessLevel::Advocate,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "serverperformance",
        handler: "HandleServerPerformance",
        source: "Command/Handlers/AdminStatCommands.cs",
        description: "Displays a summary of server performance statistics",
        usage: "",
        access: AccessLevel::Advocate,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "serverstatus",
        handler: "HandleServerStatus",
        source: "Command/Handlers/AdminStatCommands.cs",
        description: "Displays a summary of server statistics and usage",
        usage: "",
        access: AccessLevel::Advocate,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "tele",
        handler: "HandleTele",
        source: "Command/Handlers/AdvocateCommands.cs",
        description: "Teleports you(or a player) to some location.",
        usage: "[name] <longitude> <latitude>\nExample: /tele 0n0w\nExample: /tele plats4days 37s,67w\nThis command teleports yourself (or the specified character) to the given longitude and latitude.",
        access: AccessLevel::Advocate,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
