//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "netstats",
        handler: "HandleNetStats",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "View network statistics",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "nudge",
        handler: "HandleNudge",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Adjusts the spawn position of a landblock instance",
        usage: "<dir> <amount>\nDirections: x, y, z, north, south, west, east, northwest, northeast, southwest, southeast, n, s, w, e, nw, ne, sw, se, up, down, here",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "pk",
        handler: "HandlePk",
        source: "Command/Handlers/AdminCommands.cs",
        description: "sets your own PK state.",
        usage: "< npk / pk / pkl / free >\nThis command sets your current player killer state\nThis command also expects to be used '@cloak player' to properly reflect to other players\n< npk > You can only attack monsters.\n< pk > You can attack player killers and monsters.\n< pkl > You can attack player killer lites and monsters\n< free > You can attack players, player killers, player killer lites, monsters, and npcs",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "pktimer",
        handler: "HandlePKTimer",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Sets your PK timer to the current time",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "playsound",
        handler: "HandlePlaySound",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Plays a sound.",
        usage: "sound (volume) (guid)\nSound can be uint or enum name\nVolume and source guid are optional",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "portalstorm",
        handler: "HandlePortalStorm",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Tests starting a portal storm on yourself",
        usage: "storm_level [0=Brewing, 1=Imminent, 2=Stormed, 3=Subsided]",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "propertydump",
        handler: "HandlePropertyDump",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Lists all properties for the last world object you examined.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "pscript",
        handler: "HandlePScript",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "purchase-house",
        handler: "HandlePurchaseHouse",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Instantly purchase the house for the last appraised covenant crystal.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "qst",
        handler: "Handleqst",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Query, stamp, and erase quests on the targeted player",
        usage: "(fellow) [list | bestow | erase]\nqst list - List the quest flags for the targeted player\nqst bestow - Stamps the specific quest flag on the targeted player. If this fails, it's probably because you spelled the quest flag wrong.\nqst stamp - Stamps the specific quest flag on the targeted player the specified number of times. If this fails, it's probably because you spelled the quest flag wrong.\nqst erase - Erase the specific quest flag from the targeted player. If no quest flag is given, it erases the entire quest table for the targeted player.\n",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "radar",
        handler: "Handleradar",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "raise",
        handler: "HandleRaise",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "rares dump",
        handler: "HandleRaresDump",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "readdat",
        handler: "ReadDat",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Tests reading the client_portal.dat",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "recordcast",
        handler: "HandleRecordCast",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Records spell casting keypresses to server for debugging",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "reload-landblock",
        handler: "HandleReloadLandblocks",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Reloads the current landblock.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "reloadsysmsg",
        handler: "Handlereloadsysmsg",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "remove-vitae",
        handler: "HandleRemoveVitae",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Removes vitae from last appraised player",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "removeenc",
        handler: "HandleRemoveEnc",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Removes the last appraised object from the encounters table",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "removeinst",
        handler: "HandleRemoveInst",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Removes the last appraised object from the current landblock instances",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "removeitemspell",
        handler: "HandleRemoveItemSpell",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Removes a spell to the last appraised item's spellbook.",
        usage: "<spell id>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "removespell",
        handler: "HandleRemoveSpell",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Removes the specified spell to your own spellbook.",
        usage: "<spellid>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "requirecomps",
        handler: "HandleRequireComps",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Sets whether spell components are required to cast spells.",
        usage: "[ on | off ]\nThis command sets whether spell components are required to cast spells..\n When turned on, spell components are required.\n When turned off, spell components are ignored.",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "resist-info",
        handler: "HandleResistInfo",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the resistance info for the last appraised creature.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "retaliatetargets",
        handler: "HandleRetaliateTargets",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the list of retaliate targets for a monster",
        usage: "<optional guid, or optional 'target' for last appraisal target>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "rip",
        handler: "HandleRip",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "rotate",
        handler: "HandleRotate",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Adjusts the rotation of a landblock instance",
        usage: "<dir>\nDirections: north, south, west, east, northwest, northeast, southwest, southeast, n, s, w, e, nw, ne, sw, se, -or-\n0-360, with 0 being north, and 90 being west",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "rotate-x",
        handler: "HandleRotateX",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Adjusts the rotation of a landblock instance along the x-axis",
        usage: "<degrees>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "rotate-y",
        handler: "HandleRotateY",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Adjusts the rotation of a landblock instance along the y-axis",
        usage: "<degrees>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "rotate-z",
        handler: "HandleRotateZ",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Adjusts the rotation of a landblock instance along the z-axis",
        usage: "<degrees>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "safecomps",
        handler: "HandleSafeComps",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Enables / disables spell component burning",
        usage: "<on/off>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "save-now",
        handler: "HandleSaveNow",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Saves your session.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "setadvclass",
        handler: "Handlesetadvclass",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "setcoin",
        handler: "HandleSetCoin",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Set Coin display debug only usage",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "setglobalenviron",
        handler: "HandleSetGlobalEnviron",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sets or clears server's global environment option",
        usage: "(name or id of EnvironChangeType)\nleave blank to reset to default.\nlist to get a complete list of options.",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "sethealth",
        handler: "HandleSetHealth",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "sets your current health to a specific value.",
        usage: "ushort",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "setlbenviron",
        handler: "HandleSetLBEnviron",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sets or clears your current landblock's environment option",
        usage: "(name or id of EnvironChangeType)\nleave blank to reset to default.\nlist to get a complete list of options.",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "setposition",
        handler: "HandleSetPosition",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Saves the supplied character position type to the database.",
        usage: "uint 1-27\n@setposition 1",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "setproperty",
        handler: "HandleSetProperty",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Sets a property for the last appraised object",
        usage: "<property> <value>",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "setpurchasetime",
        handler: "HandleSetPurchaseTime",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Sets the house purchase time for this player",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "setvital",
        handler: "SetVital",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Sets the specified vital to a specified value",
        usage: "Usage: @setvital <vital> <value>\n<vital> is one of the following strings:\n    health, hp\n    stamina, stam, sp\n    mana, mp\n<value> is an integral value [0-9]+, or a relative value [-+][0-9]+",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "show-wielded-treasure",
        handler: "HandleShowWieldedTreasure",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the WieldedTreasure table for a Creature",
        usage: "wcid",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "showsession",
        handler: "HandleShowSession",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Show IP and ID for network session of last appraised character",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "showstats",
        handler: "HandleShowStats",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows a list of a creature's current attribute/skill levels",
        usage: "showstats",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "showtier",
        handler: "HandleShowTier",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the DeathTreasure tier for the last appraised monster",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "showvelocity",
        handler: "HandleShowVelocity",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the velocity of the last appraised object.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "slow",
        handler: "HandleSlow",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "spendallxp",
        handler: "HandleSpendAllXp",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Spend all available XP on Attributes, Vitals and Skills.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "spendxp",
        handler: "HandleSpendxp",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "splits",
        handler: "HandleSplits",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Creates some stackable items in your inventory for testing.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "sticky",
        handler: "HandleSticky",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sets whether you lose items should you die.",
        usage: "<off/on>",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
