//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "addallspells",
        handler: "HandleAddAllSpells",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Adds all known spells to your own spellbook.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "addalltitles",
        handler: "HandleAddAllTitles",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Add all titles to yourself",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "addenc",
        handler: "HandleAddEncounter",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Spawns a new wcid or classname in the current outdoor cell as an encounter",
        usage: "<wcid or classname>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "additemspell",
        handler: "HandleAddItemSpell",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Adds a spell to the last appraised item's spellbook.",
        usage: "<spell id>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "addspell",
        handler: "HandleAddSpell",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Adds the specified spell to your own spellbook.",
        usage: "<spellid>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "addtitle",
        handler: "HandleAddTitle",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Add title to yourself",
        usage: "[titleid]",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "adminui",
        handler: "HandleAdminui",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "animation",
        handler: "Animation",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Plays an animation on the current player, or optionally another object",
        usage: "MotionCommand (optional target guid)\n",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "auditobjectmaint",
        handler: "HandleAuditObjectMaint",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Iterates over physics objects to find leaks",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "barbershop",
        handler: "BarberShop",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Displays the barber ui",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "barrier-test",
        handler: "HandleBarrierTest",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows debug information for house barriers",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "bumpvelocity",
        handler: "HandleBumpVelocity",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Bumps the velocity of the last appraised object.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "castspell",
        handler: "HandleCastSpell",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Casts a spell on the last appraised object",
        usage: "spell id",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "chatdump",
        handler: "ChatDump",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Spews 1000 lines of text to you.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "check-collision",
        handler: "HandleCheckEthereal",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Checks if the player is currently colliding with any other objects.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "ci",
        handler: "HandleCI",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Creates an object in your inventory.",
        usage: "wclassid (string or number), Amount to Spawn (optional [default:1]), Palette (optional), Shade (optional)\n",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "ciaetheria",
        handler: "HandleCIAetheria",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Spawns an Aetheria in the player's inventory",
        usage: "[color] [set] [surge] [level]\nColor: Blue, Yellow, Red\nSet: Defense, Destruction, Fury, Growth, Vigor\nSurge: Destruction, Protection, Regeneration, Affliction, Festering\nLevel: 1 - 5",
        access: AccessLevel::Developer,
        min_args: 4,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "ciloot",
        handler: "HandleCILoot",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Generates randomized loot in player's inventory",
        usage: "<tier> optional: <# items>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "cirand",
        handler: "HandleCIRandom",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Creates random objects in your inventory.",
        usage: "type (string or number) <num to create> defaults to 10 if omitted, max 50",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "cisalvage",
        handler: "HandleCISalvage",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Create a salvage bag in your inventory",
        usage: "<material_type>, optional: <structure> <workmanship> <num_items>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "clearcache",
        handler: "HandleClearCache",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Clears the various database caches. This enables live editing of the database information",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "clearphysicscaches",
        handler: "HandleClearPhysicsCaches",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Clears Physics Object Caches",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "cm",
        handler: "HandleCM",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Create a salvage bag in your inventory",
        usage: "<material_type>, optional: <structure> <workmanship> <num_items>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "comps",
        handler: "HandleComps",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Creates spell component items in your inventory for testing.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "contract",
        handler: "HandleContract",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Query, stamp, and erase contracts on the targeted player",
        usage: "[list | bestow | erase]\ncontract list - List the contracts for the targeted player\ncontract bestow - Stamps the specific contract on the targeted player. If this fails, it's probably because the contract is invalid.\ncontract erase - Erase the specific contract from the targeted player. If no quest flag is given, it erases the entire contract table for the targeted player.\n",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "copychar",
        handler: "HandleCopychar",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Copies an existing character into your character list.",
        usage: "< Existing Character Name >, < New Character Name >\nGiven the name of an existing character \"character name\", this command makes a copy of that character with the name \"copy name\" and places it into your character list.",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "create",
        handler: "HandleCreate",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Creates an object or objects in the world.",
        usage: "<wcid or classname> (amount) (palette) (shade)\nThis will attempt to spawn the weenie you specify. If you include an amount to spawn, it will attempt to create that many of the object.\nStackable items will spawn in stacks of their max stack size. All spawns will be limited by the physics engine placement, which may prevent the number you specify from actually spawning.Be careful with large numbers, especially with ethereal weenies.",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "createinst",
        handler: "HandleCreateInst",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Spawns a new wcid or classname as a landblock instance",
        usage: "<wcid or classname>\n\nTo create a parent/child relationship: /createinst -p <parent guid> -c <wcid or classname>\nTo automatically get the parent guid from the last appraised object: /createinst -p -c <wcid or classname>\n\nTo manually specify a start guid: /createinst <wcid or classname> <start guid>\nStart guids can be in the range 0x000-0xFFF, or they can be prefixed with 0x7<landblock id>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "createliveops",
        handler: "HandleCreateLiveOps",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Creates an object or objects with lifespans in the world for live events.",
        usage: "<wcid or classname> (amount) (lifespan) (palette) (shade)\nThis will attempt to spawn the weenie you specify. If you include an amount to spawn, it will attempt to spawn that many of the object.\nStackable items will spawn in stacks of their max stack size. All spawns will be limited by the physics engine placement, which may prevent the number you specify from actually spawning.\nBe careful with large numbers, especially with ethereal weenies.\nIf you include a lifespan, this value is in seconds, and defaults to 3600 (1 hour) if not specified.",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "createnamed",
        handler: "HandleCreateNamed",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Creates a named object in the world.",
        usage: "<wcid or classname> <count> <name>",
        access: AccessLevel::Developer,
        min_args: 3,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "currency",
        handler: "HandleCurrency",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Creates some currency items in your inventory for testing.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "damagehistory",
        handler: "HandleDamageHistory",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "database-shard-cache-npbrt",
        handler: "HandleDatabaseShardCacheNPBRT",
        source: "Command/Handlers/DeveloperDatabaseCommands.cs",
        description: "Shard Database, Non-Player Biota Cache - Retention Time (in minutes)",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "database-shard-cache-pbrt",
        handler: "HandleDatabaseShardCachePBRT",
        source: "Command/Handlers/DeveloperDatabaseCommands.cs",
        description: "Shard Database, Player Biota Cache - Retention Time (in minutes)",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "databaseperftest",
        handler: "HandleDatabasePerfTest",
        source: "Command/Handlers/DeveloperDatabaseCommands.cs",
        description: "Test server/database performance.",
        usage: "biotasPerTest\noptional parameter biotasPerTest if omitted 1000",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "databasequeueinfo",
        handler: "HandleDatabaseQueueInfo",
        source: "Command/Handlers/DeveloperDatabaseCommands.cs",
        description: "Show database queue information.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "de_n",
        handler: "Handlede_n",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends text to named player, formatted exactly as entered.",
        usage: "<name>, <text>",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "de_s",
        handler: "Handlede_s",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends text to selected player, formatted exactly as entered, with no prefix of any kind.",
        usage: "<text>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "deathxp",
        handler: "HandleDeathxp",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Displays how much experience the last appraised creature is worth when killed.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugboard",
        handler: "HandleDebugBoard",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the current chess board state",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugchess",
        handler: "HandleDebugChess",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the chess move history for a player",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugdamage",
        handler: "HandleDebugDamage",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Toggles the display for player damage info",
        usage: "<attack|defense|all|on|off>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugemote",
        handler: "HandleDebugEmote",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Enables emote debugging for the last appraised object",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugmove",
        handler: "ToggleMovementDebug",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Toggles movement debugging for the last appraised monster",
        usage: "<on/off>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugspell",
        handler: "HandleDebugSpell",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Toggles spell projectile debugging info",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugspellbook",
        handler: "HandleDebugSpellbook",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the spellbook for the last appraised object",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "delevel",
        handler: "HandleDelevel",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Attempts to delevel the current player. Requires enough unassigned xp and unspent skill credits.",
        usage: "new level",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "destructionqueue",
        handler: "HandleDestructionQueue",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the list of previously visible objects queued for destruction for a player",
        usage: "<optional guid, or optional 'target' for last appraisal target>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "direct_emote_name",
        handler: "Handledirect_emote_name",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends text to named player, formatted exactly as entered.",
        usage: "<name>, <text>",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "direct_emote_select",
        handler: "Handledirect_emote_select",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends text to selected player, formatted exactly as entered, with no prefix of any kind.",
        usage: "<text>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "dispel",
        handler: "HandleDispel",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Removes all enchantments from the player",
        usage: "/dispel",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "dist",
        handler: "HandleDist",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Returns the distance to the last appraised object",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "draw",
        handler: "HandleDraw",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "dumpattackers",
        handler: "Handledumpattackers",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "dungeonname",
        handler: "HandleDungeonName",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the dungeon name for the current landblock",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "echo",
        handler: "HandleDebugEcho",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Send text back to yourself.",
        usage: "\"text to send back to yourself\" [ChatMessageType]\nChatMessageType can be a uint or enum name",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "echoflags",
        handler: "HandleDebugEchoFlags",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Echo flags back to you",
        usage: "[type to test] [int]\n",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "effect",
        handler: "HandlePlayEffect",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Plays an effect.",
        usage: "effect (float)\nEffect can be uint or enum namefloat is scale level",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "enable-aetheria",
        handler: "HandleEnableAetheria",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Enables the aetheria slots for the player",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "equiptest",
        handler: "EquipTest",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Simulates equipping a new item to your character, replacing all other items.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "event",
        handler: "HandleEvent",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Maniuplates the state of an event",
        usage: "[ start | stop | disable | enable | clear | status ] (name)\n@event clear < name > - clears event with name <name> or all events if you put in 'all' (All clears registered generators, <name> does not)\n@event status <eventSubstring> - get the status of all registered events or get all of the registered events that have <eventSubstring> in the name.",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "export-json",
        handler: "HandleExportJson",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Exports content from database to JSON file",
        usage: "<optional type> <id>\n<optional type> - landblock, quest, recipe, spell, weenie (default if not specified)\n<id> - wcid or content id to export",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "export-json-folders",
        handler: "HandleExportJsonFolder",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Exports content from database to JSON file in a WeenieType/ItemType folder structure",
        usage: "<wcid>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "export-sql",
        handler: "HandleExportSql",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Exports content from database to SQL file",
        usage: "<optional type> <id>\n<optional type> - landblock, encounter, event, quest, recipe, spell, weenie (default if not specified)\n<id> - wcid or content id to export",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "export-sql-folders",
        handler: "HandleExportSqlFolder",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Exports weenie content from database to an SQL file in a WeenieType/ItemType folder structure",
        usage: "<wcid>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "faction",
        handler: "HandleFaction",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "sets your own faction state.",
        usage: "< none / ch / ew / rb > (rank)\nThis command sets your current faction state\n< none > No Faction\n< ch > Celestial Hand\n< ew > Eldrytch Web\n< rb > Radiant Blood\n(rank) 1 = Initiate | 2 = Adept | 3 = Knight | 4 = Lord | 5 = Master",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fast",
        handler: "HandleFast",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fellow-dist",
        handler: "HandleFellowDist",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows distance to each fellowship member",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fellow-info",
        handler: "HandleFellowInfo",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows debug info for fellowships.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "food",
        handler: "HandleFood",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Creates some food items in your inventory for testing.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "forcegc",
        handler: "HandleForceGC",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Forces .NET Garbage Collection",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "forcegc2",
        handler: "HandleForceGC2",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Forces .NET Garbage Collection with LOH Compact",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "forcelogoff",
        handler: "HandleForceLogoff",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Force log off of specified character or last appraised character",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "forcelogout",
        handler: "HandleForceLogout",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Force log off of specified character or last appraised character",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fumble",
        handler: "HandleFumble",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
