//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "MoveTo",
        handler: "MoveTo",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Used to test the MoveToObject message.   It will spawn a training wand in front of you and then move to that object.",
        usage: "moveto\noptional parameter distance if omitted 10f",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "gamecastemote",
        handler: "HandleGameCastEmote",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends text to all players, formatted exactly as entered.",
        usage: "<message>\nSee Also: @gamecast, @gamecastemote, @gamecastlocal, @gamecastlocalemote.",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "gamecastlocal",
        handler: "HandleGameCastLocal",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends a server-wide broadcast.",
        usage: "<message>\nThis command sends the specified text to every player on the current server.\nSee Also: @gamecast, @gamecastemote, @gamecastlocal, @gamecastlocalemote.",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "gamecastlocalemote",
        handler: "HandleGameCastLocalEmote",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends text to all players within chat range, formatted exactly as entered.",
        usage: "<message>\nSends text to all players within chat range, formatted exactly as entered, with no prefix of any kind.\nSee Also: @gamecast, @gamecastemote, @gamecastlocal, @gamecastlocalemote.",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "generate-classnames",
        handler: "HandleGenerateClassNames",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Generates WeenieClassName.cs from current world database",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "generatordump",
        handler: "HandleGeneratorDump",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Lists all properties for the last generator you examined.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "getallspellformula",
        handler: "GetAllSpellFormula",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Tests spell formula calculation",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "getinfo",
        handler: "HandleGetInfo",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows basic info for the last appraised object.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "getproperty",
        handler: "HandleGetProperty",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Gets a property for the last appraised object",
        usage: "<property>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "getspellformula",
        handler: "GetSpellFormula",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Tests spell formula calculation",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "givemana",
        handler: "HandleGiveMana",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Gives mana to the last appraised object",
        usage: "<amount>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "gps",
        handler: "HandleDebugGPS",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Display location.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "grantitemxp",
        handler: "HandleGrantItemXp",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Give item XP to the last appraised item.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "grantluminance",
        handler: "HandleGrantLuminance",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Give luminance to yourself (or the specified character).",
        usage: "ulong\n@grantluminance [name] 1500000 is max luminance",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "grantxp",
        handler: "HandleGrantXp",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Give XP to yourself (or the specified character).",
        usage: "ulong\n@grantxp [name] 191226310247 is max level 275",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "harmself",
        handler: "HarmSelf",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Sets all player vitals to 1",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "housekeep",
        handler: "HandleHousekeep",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "idlist",
        handler: "HandleIDlist",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Shows the next ID that will be allocated from GuidManager.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "import-json",
        handler: "HandleImportJson",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Imports json data from the Content folder",
        usage: "<type> <wcid>\n<type> - landblock, quest, recipe, spell, weenie (default if not specified)\n<wcid> - filename prefix to search for. can be 'all' to import all files for this content type",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "import-sql",
        handler: "HandleImportSQL",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Imports sql data from the Content folder",
        usage: "<type> <wcid>\n<type> - landblock, encounter, quest, recipe, spell, weenie (default if not specified)\n<wcid> - filename prefix to search for. can be 'all' to import all files for this content type",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "import-sql-folders",
        handler: "HandleImportSQLFolders",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Imports all weenie sql data from the Content folder and all sub-folders",
        usage: "<wcid>\n<wcid> - wcid prefix to search for. can be 'all' to import everything",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "inv",
        handler: "HandleInv",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Creates sample items, foci and containers in your inventory.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "knownobjs",
        handler: "HandleKnownObjs",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the list of objects currently known to an object",
        usage: "<optional guid, or optional 'target' for last appraisal target>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "knownplayers",
        handler: "HandleKnownPlayers",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the list of players known to an object",
        usage: "<optional guid, or optional 'target' for last appraisal target>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "listcb",
        handler: "HandleShowCompatibleClothingBases",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "List Clothing Tables available",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: true,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "listplayers",
        handler: "HandleListPlayers",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Displays all of the active players connected too the server.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "listpositions",
        handler: "HandleListPositions",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Displays all available saved character positions from the database.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "loadalllandblocks",
        handler: "HandleLoadAllLandblocks",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Loads all Landblocks. This is VERY crude. Do NOT use it on a live server!!! It will likely crash the server.  Landblock resources will be loaded async and will continue to do work even after all landblocks have been loaded.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "location",
        handler: "HandleLocation",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "lootgen",
        handler: "HandleLootGen",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Generate a piece of loot from the LootGenerationFactory.",
        usage: "<wcid or classname> <tier>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "lostest",
        handler: "HandleVisible",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Tests for direct visibilty with latest appraised object",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "magic god",
        handler: "HandleMagicGod",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "makeiou",
        handler: "HandleMakeIOU",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Make an IOU and put it in your inventory",
        usage: "<wcid>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "mod",
        handler: "HandleListMods",
        source: "Mods/ModCommands.cs",
        description: "Lazy mod control",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "monsterspell",
        handler: "HandleMonsterProj",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "The last appraised creature casts a spell. For targeted spells, defaults to the current player.",
        usage: "optional target guid",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "morph",
        handler: "HandleMorph",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Morphs your bodily form into that of the specified creature. Be careful with this one!",
        usage: "<wcid or weenie class name> [character name]",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "movement",
        handler: "Movement",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Movement testing command, to be removed soon",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "myloc",
        handler: "HandleMyLoc",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the current player location, from the server perspective",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
