//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "targetloc",
        handler: "HandleTargetLoc",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the location of the last appraised object",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "teleallto",
        handler: "HandleTeleAllTo",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Teleports all players to a player. If no target is specified, all players will be teleported to you.",
        usage: "[Player's Name]\n",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "teledist",
        handler: "HandleTeleportDist",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Teleports a some distance ahead of the last object spawned",
        usage: "<distance>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "teledungeon",
        handler: "HandleTeleDungeon",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Teleport to a dungeon",
        usage: "<dungeon name or landblock>",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "teleloc",
        handler: "HandleTeleportLOC",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Teleport yourself to the specified location.",
        usage: "cell [x y z] (qw qx qy qz)\n@teleloc follows the same number order as displayed from @loc output\nExample: @teleloc 0x7F0401AD [12.319900 -28.482000 0.005000] -0.338946 0.000000 0.000000 -0.940806\nExample: @teleloc 0x7F0401AD 12.319900 -28.482000 0.005000 -0.338946 0.000000 0.000000 -0.940806\nExample: @teleloc 7F0401AD 12.319900 -28.482000 0.005000",
        access: AccessLevel::Developer,
        min_args: 4,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "telepoi",
        handler: "HandleTeleportPoi",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Teleport yourself to a named Point of Interest",
        usage: "[POI|list]\n@telepoi Arwic\nGet the list of POIs\n@telepoi list",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "teletype",
        handler: "HandleTeleType",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Teleport to a saved character position.",
        usage: "uint 0-22\n@teletype 1",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "telexyz",
        handler: "HandleDebugTeleportXYZ",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Teleport to a location.",
        usage: "cell x y z qx qy qz qw\nall parameters must be specified and cell must be in decimal form",
        access: AccessLevel::Developer,
        min_args: 8,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "testaim",
        handler: "HandleTestAim",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Tests the aim high/low motions, and projectile spawn position",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "testdeathitems",
        handler: "HandleTestDeathItems",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Test death item selection",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "tiermobs",
        handler: "HandleTierMobs",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows a list of monsters for a particular tier #",
        usage: "tier",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "trainskill",
        handler: "Handletrainskill",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "trywield",
        handler: "HandleTryWield",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "turnto",
        handler: "HandleRequestTurnTo",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Turns the last appraised object to the player",
        usage: "turnto",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "usewith",
        handler: "HandleUseWithTarget",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Uses specified object on last appraised object",
        usage: "guid",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "vendordump",
        handler: "HandleVendorDump",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Lists all properties for the last vendor you examined.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "visibleobjs",
        handler: "HandleVisibleObjs",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the list of objects currently visible to an object",
        usage: "<optional guid, or optional 'target' for last appraisal target>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "visibleplayers",
        handler: "HandleVisiblePlayers",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the list of players visible to a player",
        usage: "<optional guid, or optional 'target' for last appraisal target>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "visibletargets",
        handler: "HandleVisibleTargets",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows the list of targets currently visible to a monster",
        usage: "<optional guid, or optional 'target' for last appraisal target>",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "vloc2loc",
        handler: "HandleVLOCtoLOC",
        source: "Command/Handlers/DeveloperContentCommands.cs",
        description: "Output a set of LOCs for a given landblock found in the VLOCS dataset",
        usage: "<LandblockID>\nExample: @vloc2loc 0x0007\n         @vloc2loc 0xCE95",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "we",
        handler: "HandleWe",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends text to all players, formatted exactly as entered.",
        usage: "<message>\nSee Also: @gamecast, @gamecastemote, @gamecastlocal, @gamecastlocalemote.",
        access: AccessLevel::Developer,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "weapons",
        handler: "HandleWeapons",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Creates testing items in your inventory.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "whoami",
        handler: "HandleWhoAmI",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Shows you your GUIDs.",
        usage: "",
        access: AccessLevel::Developer,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
