//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "crack",
        handler: "HandleCrack",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Cracks the most recently appraised locked target.",
        usage: "[. open it too]",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "delete",
        handler: "HandleDeleteSelected",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Deletes the selected object.",
        usage: "Players may not be deleted this way.",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "gamecast",
        handler: "HandleGamecast",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends a world-wide broadcast.",
        usage: "<message>\nThis command sends a world-wide broadcast to everyone in the game. Text is prefixed with 'Broadcast from (admin-name)> '.\nSee Also: @gamecast, @gamecastemote, @gamecastlocal, @gamecastlocalemote.",
        access: AccessLevel::Envoy,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "heal",
        handler: "HandleHeal",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Heals yourself (or the selected creature)",
        usage: "\nThis command fully restores your(or the selected creature's) health, mana, and stamina",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "myiid",
        handler: "HandleMyIID",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Displays your Instance ID (IID)",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "myserver",
        handler: "HandleMyServer",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "queryplugin",
        handler: "HandleQueryplugin",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "querypluginlist",
        handler: "HandleQuerypluginlist",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "regen",
        handler: "HandleRegen",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sends the selected generator a regeneration message.",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "rename",
        handler: "HandleRename",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Rename a character. (Do NOT include +'s for admin names)",
        usage: "< Current Name >, < New Name >",
        access: AccessLevel::Envoy,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "serverlist",
        handler: "HandleServerlist",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "smite",
        handler: "HandleSmite",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Kills the selected target or all monsters in radar range if \"all\" is specified.",
        usage: "[all, Player's Name]",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "snoop",
        handler: "HandleSnoop",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "time",
        handler: "HandleTime",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Displays the server's current game time.",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "trophies",
        handler: "HandleTrophies",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Shows a list of the trophies dropped by the target creature, and the percentage chance of dropping.",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "unlock",
        handler: "HandleUnlock",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Envoy,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
];
