//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "acecommands",
        handler: "HandleACECommands",
        source: "Command/Handlers/HelpCommands.cs",
        description: "Lists all commands.",
        usage: "<access level or search>",
        access: AccessLevel::Player,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "acehelp",
        handler: "HandleACEHelp",
        source: "Command/Handlers/HelpCommands.cs",
        description: "Displays help.",
        usage: "(command)",
        access: AccessLevel::Player,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "aceversion",
        handler: "HandleACEversion",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Shows this server's version data",
        usage: "",
        access: AccessLevel::Player,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "castmeter",
        handler: "HandleCastMeter",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Shows the fast casting efficiency meter",
        usage: "",
        access: AccessLevel::Player,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "config",
        handler: "HandleConfig",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Manually sets a character option on the server.\nUse /config list to see a list of settings.",
        usage: "<setting> <on/off>",
        access: AccessLevel::Player,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "debugcast",
        handler: "HandleDebugCast",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Shows debug information about the current magic casting state",
        usage: "",
        access: AccessLevel::Player,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fixbusy",
        handler: "HandleFixBusy",
        source: "Command/Handlers/DeveloperCommands.cs",
        description: "Attempts to remove the hourglass / fix the busy state for the player",
        usage: "",
        access: AccessLevel::Player,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "fixcast",
        handler: "HandleFixCast",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Fixes magic casting if locked up for an extended time",
        usage: "",
        access: AccessLevel::Player,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "house-select",
        handler: "HandleHouseSelect",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "For characters/accounts who currently own multiple houses, used to select which house they want to keep",
        usage: "",
        access: AccessLevel::Player,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "myquests",
        handler: "HandleQuests",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Shows your quest log",
        usage: "",
        access: AccessLevel::Player,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "objsend",
        handler: "HandleObjSend",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Force resend of all visible objects known to this player. Can fix rare cases of invisible object bugs. Can only be used once every 5 mins max.",
        usage: "",
        access: AccessLevel::Player,
        min_args: -1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "passwd",
        handler: "HandlePasswd",
        source: "Command/Handlers/AccountCommands.cs",
        description: "Change your account password.",
        usage: "oldpassword newpassword\n",
        access: AccessLevel::Player,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "pop",
        handler: "HandlePop",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Show current world population",
        usage: "",
        access: AccessLevel::Player,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "reportbug",
        handler: "HandleReportbug",
        source: "Command/Handlers/PlayerCommands.cs",
        description: "Generate a Bug Report",
        usage: "<category> <description>\nThis command generates a URL for you to copy and paste into your web browser to submit for review by server operators and developers.\nCategory can be the following:\nCreature\nNPC\nItem\nQuest\nRecipe\nLandblock\nMechanic\nCode\nOther\nFor the first three options, the bug report will include identifiers for what you currently have selected/targeted.\nAfter category, please include a brief description of the issue, which you can further detail in the report on the website.\nExamples:\n/reportbug creature Drudge Prowler is over powered\n/reportbug npc Ulgrim doesn't know what to do with Sake\n/reportbug quest I can't enter the portal to the Lost City of Frore\n/reportbug recipe I cannot combine Bundle of Arrowheads with Bundle of Arrowshafts\n/reportbug code I was killed by a Non-Player Killer\n",
        access: AccessLevel::Player,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
