//! Generated from pinned official ACE command attributes; AGPL-3.0-only.
use super::CommandSpec;
use bace_auth::AccessLevel;
pub(super) static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        name: "adminvision",
        handler: "HandleAdminvision",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Allows the admin to see admin-only visible items.",
        usage: "{ on | off | toggle | check }\nControls whether or not the admin can see admin-only visible items. Note that if you turn this feature off, you will need to log out and back in before the visible items become invisible.",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "ban",
        handler: "HandleBanAccount",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Bans the specified player account.",
        usage: "[accountname] [days] [hours] [minutes] (reason)\nThis command bans the specified player account for the specified time. This player will not be able to enter the game with any character until the time expires.\nExample: @ban AccountName 0 0 5\nExample: @ban AccountName 1 0 0 banned 1 day because reasons\n",
        access: AccessLevel::Sentinel,
        min_args: 4,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "banlist",
        handler: "HandleBanlist",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Lists all banned accounts on this world.",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "boot",
        handler: "HandleBoot",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Boots the character out of the game.",
        usage: "[account | char | iid] who (, reason) \nThis command boots the specified character out of the game. You can specify who to boot by account, character name, or player instance id. 'who' is the account / character / instance id to actually boot. You can optionally include a reason for the boot.\nExample: @boot char Character Name\n         @boot account AccountName\n         @boot iid 0x51234567\n         @boot char Character Name, Reason for being booted\n",
        access: AccessLevel::Sentinel,
        min_args: 2,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "buff",
        handler: "HandleBuff",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Buffs you (or a player) with all beneficial spells.",
        usage: "[name] [maxLevel]\nThis command buffs yourself (or the specified character).",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "cloak",
        handler: "HandleCloak",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Sets your cloaking state.",
        usage: "< on / off / player / creature >\nThis command sets your current cloaking state\n< on > You will be completely invisible to players.\n< off > You will show up as a normal.\n< player > You will appear as a player. (No + and a white radar dot.)\n< creature > You will appear as a creature. (No + and an orange radar dot.)",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "deaf",
        handler: "HandleDeafHearOrMute",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "fellowbuff",
        handler: "HandleFellowBuff",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Buffs your fellowship (or a player's fellowship) with all beneficial spells.",
        usage: "[name]\nThis command buffs your fellowship (or the fellowship of the specified character).",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "finger",
        handler: "HandleFinger",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Show the given character's account name or vice-versa.",
        usage: "[ [-a] character] [-m account]\nGiven a character name, this command displays the name of the owning account.\nIf the -m option is specified, the argument is considered an account name and the characters owned by that account are displayed.\nIf the -a option is specified, then the character name is fingered but their account is implicitly fingered as well.",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "freeze",
        handler: "HandleFreeze",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "gag",
        handler: "HandleGag",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Prevents a character from talking.",
        usage: "< char name >\nThe character will not be able to @tell or use chat normally.",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "god",
        handler: "HandleGod",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Turns current character into a god!",
        usage: "Sets attributes and skills to higher than max levels.\nTo return to a mortal state, use the /ungod command.\nUse the /god command with caution. While unlikely, there is a possibility that the character that runs the command will not be able to return to normal or will end up in a state that is unrecoverable.",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "home",
        handler: "HandleHome",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Teleports you to your sanctuary position.",
        usage: "< recall number > - Recalls to a saved position, valid values are 1 - 9.\nNOTE: Calling @home without a number recalls your sanctuary position; calling it with a number will teleport you to the corresponding saved position.",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "limbo",
        handler: "HandleLimbo",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "mrt",
        handler: "HandleMRT",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Toggles the ability to bypass housing boundaries",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "neversaydie",
        handler: "HandleNeverSayDie",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Turn immortality on or off.",
        usage: "[ on | off ]\nDefaults to on.",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "portal_bypass",
        handler: "HandlePortalBypass",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Toggles the ability to bypass portal restrictions.",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "repeat",
        handler: "HandleRepeat",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 2,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "run",
        handler: "HandleRun",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Temporarily boosts your run skill.",
        usage: "( on | off | toggle | check )\nBoosts the run skill of the PSR so they can pursue the \"bad folks\". The enchantment will wear off after a while. This command defaults to toggle.",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "save",
        handler: "HandleSave",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Sets your sanctuary position or a named recall point.",
        usage: "< recall number > - Saves your position into the numbered recall, valid values are 1 - 9.\nNOTE: Calling @save without a number saves your sanctuary (Lifestone Recall) position.",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "telereturn",
        handler: "HandleTeleReturn",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Return a player to their previous location.",
        usage: "PlayerName",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "teleto",
        handler: "HandleTeleto",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Teleport yourself to a player",
        usage: "[Player's Name]\n",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "teletome",
        handler: "HandleTeleToMe",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Teleports a player to your current location.",
        usage: "PlayerName",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "unban",
        handler: "HandleUnBanAccount",
        source: "Command/Handlers/SentinelCommands.cs",
        description: "Unbans the specified player account.",
        usage: "[accountname]\nThis command removes the ban from the specified account. The player will then be able to log into the game.",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: false,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "unfreeze",
        handler: "HandleUnFreeze",
        source: "Command/Handlers/AdminCommands.cs",
        description: "",
        usage: "",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: true,
    },
    CommandSpec {
        name: "ungag",
        handler: "HandleUnGag",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Allows a gagged character to talk again.",
        usage: "< char name >\nThe character will again be able to @tell and use chat normally.",
        access: AccessLevel::Sentinel,
        min_args: 1,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
    CommandSpec {
        name: "ungod",
        handler: "HandleUngod",
        source: "Command/Handlers/AdminCommands.cs",
        description: "Returns character to a mortal state.",
        usage: "Sets attributes and skills back to the values they were when you became a god.\nIf the command fails to revert your state it will default to godmode.\nIn the event of failure, contact a server administrator to sort it out.",
        access: AccessLevel::Sentinel,
        min_args: 0,
        console_only: false,
        requires_world: true,
        include_raw: false,
        source_stub: false,
    },
];
